// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 573:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum PBAthAlgorithm implements WireEnum {
  /**
   * 	��������
   */
  ATHALGO_NONE(0),

  /**
   * 	����MD5�㷨������ս����
   */
  ATHALGO_MD5(1),

  /**
   * 	����aes�㷨������ս����
   */
  ATHALGO_AES(2);

  public static final ProtoAdapter<PBAthAlgorithm> ADAPTER = ProtoAdapter.newEnumAdapter(PBAthAlgorithm.class);

  private final int value;

  PBAthAlgorithm(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static PBAthAlgorithm fromValue(int value) {
    switch (value) {
      case 0: return ATHALGO_NONE;
      case 1: return ATHALGO_MD5;
      case 2: return ATHALGO_AES;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
