// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 51:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * file upload
 */
public final class PBFileUploadInfo extends Message<PBFileUploadInfo, PBFileUploadInfo.Builder> {
  public static final ProtoAdapter<PBFileUploadInfo> ADAPTER = new ProtoAdapter_PBFileUploadInfo();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_HASH = "";

  public static final Long DEFAULT_E_TIME = 0L;

  public static final Long DEFAULT_SIZE = 0L;

  /**
   * ???????????hash?
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String hash;

  /**
   * ????????????????????900s????15????
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long e_time;

  /**
   * ????????��????�� byte
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long size;

  public PBFileUploadInfo(String hash, Long e_time, Long size) {
    this(hash, e_time, size, ByteString.EMPTY);
  }

  public PBFileUploadInfo(String hash, Long e_time, Long size, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.hash = hash;
    this.e_time = e_time;
    this.size = size;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.hash = hash;
    builder.e_time = e_time;
    builder.size = size;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBFileUploadInfo)) return false;
    PBFileUploadInfo o = (PBFileUploadInfo) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(hash, o.hash)
        && Internal.equals(e_time, o.e_time)
        && Internal.equals(size, o.size);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (hash != null ? hash.hashCode() : 0);
      result = result * 37 + (e_time != null ? e_time.hashCode() : 0);
      result = result * 37 + (size != null ? size.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (hash != null) builder.append(", hash=").append(hash);
    if (e_time != null) builder.append(", e_time=").append(e_time);
    if (size != null) builder.append(", size=").append(size);
    return builder.replace(0, 2, "PBFileUploadInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBFileUploadInfo, Builder> {
    public String hash;

    public Long e_time;

    public Long size;

    public Builder() {
    }

    /**
     * ???????????hash?
     */
    public Builder hash(String hash) {
      this.hash = hash;
      return this;
    }

    /**
     * ????????????????????900s????15????
     */
    public Builder e_time(Long e_time) {
      this.e_time = e_time;
      return this;
    }

    /**
     * ????????��????�� byte
     */
    public Builder size(Long size) {
      this.size = size;
      return this;
    }

    @Override
    public PBFileUploadInfo build() {
      if (hash == null) {
        throw Internal.missingRequiredFields(hash, "hash");
      }
      return new PBFileUploadInfo(hash, e_time, size, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBFileUploadInfo extends ProtoAdapter<PBFileUploadInfo> {
    ProtoAdapter_PBFileUploadInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, PBFileUploadInfo.class);
    }

    @Override
    public int encodedSize(PBFileUploadInfo value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.hash)
          + (value.e_time != null ? ProtoAdapter.INT64.encodedSizeWithTag(2, value.e_time) : 0)
          + (value.size != null ? ProtoAdapter.INT64.encodedSizeWithTag(3, value.size) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBFileUploadInfo value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.hash);
      if (value.e_time != null) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.e_time);
      if (value.size != null) ProtoAdapter.INT64.encodeWithTag(writer, 3, value.size);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBFileUploadInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.hash(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.e_time(ProtoAdapter.INT64.decode(reader)); break;
          case 3: builder.size(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBFileUploadInfo redact(PBFileUploadInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
