// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 90:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class PBFileDownloadRsp extends Message<PBFileDownloadRsp, PBFileDownloadRsp.Builder> {
  public static final ProtoAdapter<PBFileDownloadRsp> ADAPTER = new ProtoAdapter_PBFileDownloadRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  /**
   * ??��???>=0 ???????? <0 ??????
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  /**
   * ?????url
   */
  @WireField(
      tag = 2,
      adapter = "org.yeewoe.mopanet.protos.PBFileDownloadResult#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<PBFileDownloadResult> results;

  public PBFileDownloadRsp(Integer result, List<PBFileDownloadResult> results) {
    this(result, results, ByteString.EMPTY);
  }

  public PBFileDownloadRsp(Integer result, List<PBFileDownloadResult> results, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.results = Internal.immutableCopyOf("results", results);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.results = Internal.copyOf("results", results);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBFileDownloadRsp)) return false;
    PBFileDownloadRsp o = (PBFileDownloadRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(results, o.results);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (results != null ? results.hashCode() : 1);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (results != null) builder.append(", results=").append(results);
    return builder.replace(0, 2, "PBFileDownloadRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBFileDownloadRsp, Builder> {
    public Integer result;

    public List<PBFileDownloadResult> results;

    public Builder() {
      results = Internal.newMutableList();
    }

    /**
     * ??��???>=0 ???????? <0 ??????
     */
    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * ?????url
     */
    public Builder results(List<PBFileDownloadResult> results) {
      Internal.checkElementsNotNull(results);
      this.results = results;
      return this;
    }

    @Override
    public PBFileDownloadRsp build() {
      return new PBFileDownloadRsp(result, results, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBFileDownloadRsp extends ProtoAdapter<PBFileDownloadRsp> {
    ProtoAdapter_PBFileDownloadRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBFileDownloadRsp.class);
    }

    @Override
    public int encodedSize(PBFileDownloadRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + PBFileDownloadResult.ADAPTER.asRepeated().encodedSizeWithTag(2, value.results)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBFileDownloadRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.results != null) PBFileDownloadResult.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.results);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBFileDownloadRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.results.add(PBFileDownloadResult.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBFileDownloadRsp redact(PBFileDownloadRsp value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.results, PBFileDownloadResult.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
