// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 122:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ???????
 */
public final class PBGroupUpdateReq extends Message<PBGroupUpdateReq, PBGroupUpdateReq.Builder> {
  public static final ProtoAdapter<PBGroupUpdateReq> ADAPTER = new ProtoAdapter_PBGroupUpdateReq();

  private static final long serialVersionUID = 0L;

  /**
   * 	?????????
   */
  @WireField(
      tag = 1,
      adapter = "org.yeewoe.mopanet.protos.PBGroup#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final PBGroup group;

  public PBGroupUpdateReq(PBGroup group) {
    this(group, ByteString.EMPTY);
  }

  public PBGroupUpdateReq(PBGroup group, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.group = group;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.group = group;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBGroupUpdateReq)) return false;
    PBGroupUpdateReq o = (PBGroupUpdateReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(group, o.group);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (group != null ? group.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (group != null) builder.append(", group=").append(group);
    return builder.replace(0, 2, "PBGroupUpdateReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBGroupUpdateReq, Builder> {
    public PBGroup group;

    public Builder() {
    }

    /**
     * 	?????????
     */
    public Builder group(PBGroup group) {
      this.group = group;
      return this;
    }

    @Override
    public PBGroupUpdateReq build() {
      if (group == null) {
        throw Internal.missingRequiredFields(group, "group");
      }
      return new PBGroupUpdateReq(group, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBGroupUpdateReq extends ProtoAdapter<PBGroupUpdateReq> {
    ProtoAdapter_PBGroupUpdateReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBGroupUpdateReq.class);
    }

    @Override
    public int encodedSize(PBGroupUpdateReq value) {
      return PBGroup.ADAPTER.encodedSizeWithTag(1, value.group)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBGroupUpdateReq value) throws IOException {
      PBGroup.ADAPTER.encodeWithTag(writer, 1, value.group);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBGroupUpdateReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.group(PBGroup.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBGroupUpdateReq redact(PBGroupUpdateReq value) {
      Builder builder = value.newBuilder();
      if (builder.group != null) builder.group = PBGroup.ADAPTER.redact(builder.group);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
