// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 166:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class PBGroupGetRsp extends Message<PBGroupGetRsp, PBGroupGetRsp.Builder> {
  public static final ProtoAdapter<PBGroupGetRsp> ADAPTER = new ProtoAdapter_PBGroupGetRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  @WireField(
      tag = 2,
      adapter = "org.yeewoe.mopanet.protos.PBGroup#ADAPTER"
  )
  public final PBGroup group;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REPEATED
  )
  public final List<Long> members;

  public PBGroupGetRsp(Integer result, PBGroup group, List<Long> members) {
    this(result, group, members, ByteString.EMPTY);
  }

  public PBGroupGetRsp(Integer result, PBGroup group, List<Long> members, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.group = group;
    this.members = Internal.immutableCopyOf("members", members);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.group = group;
    builder.members = Internal.copyOf("members", members);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBGroupGetRsp)) return false;
    PBGroupGetRsp o = (PBGroupGetRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(group, o.group)
        && Internal.equals(members, o.members);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (group != null ? group.hashCode() : 0);
      result_ = result_ * 37 + (members != null ? members.hashCode() : 1);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (group != null) builder.append(", group=").append(group);
    if (members != null) builder.append(", members=").append(members);
    return builder.replace(0, 2, "PBGroupGetRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBGroupGetRsp, Builder> {
    public Integer result;

    public PBGroup group;

    public List<Long> members;

    public Builder() {
      members = Internal.newMutableList();
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    public Builder group(PBGroup group) {
      this.group = group;
      return this;
    }

    public Builder members(List<Long> members) {
      Internal.checkElementsNotNull(members);
      this.members = members;
      return this;
    }

    @Override
    public PBGroupGetRsp build() {
      return new PBGroupGetRsp(result, group, members, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBGroupGetRsp extends ProtoAdapter<PBGroupGetRsp> {
    ProtoAdapter_PBGroupGetRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBGroupGetRsp.class);
    }

    @Override
    public int encodedSize(PBGroupGetRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + (value.group != null ? PBGroup.ADAPTER.encodedSizeWithTag(2, value.group) : 0)
          + ProtoAdapter.UINT64.asRepeated().encodedSizeWithTag(3, value.members)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBGroupGetRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.group != null) PBGroup.ADAPTER.encodeWithTag(writer, 2, value.group);
      if (value.members != null) ProtoAdapter.UINT64.asRepeated().encodeWithTag(writer, 3, value.members);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBGroupGetRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.group(PBGroup.ADAPTER.decode(reader)); break;
          case 3: builder.members.add(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBGroupGetRsp redact(PBGroupGetRsp value) {
      Builder builder = value.newBuilder();
      if (builder.group != null) builder.group = PBGroup.ADAPTER.redact(builder.group);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
