// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 98:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBGroup extends Message<PBGroup, PBGroup.Builder> {
  public static final ProtoAdapter<PBGroup> ADAPTER = new ProtoAdapter_PBGroup();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_GID = 0L;

  public static final String DEFAULT_NAME = "";

  public static final String DEFAULT_DESC = "";

  /**
   * 	???id
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long gid;

  /**
   * 	?????
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String name;

  /**
   * 	???????
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String desc;

  public PBGroup(Long gid, String name, String desc) {
    this(gid, name, desc, ByteString.EMPTY);
  }

  public PBGroup(Long gid, String name, String desc, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.gid = gid;
    this.name = name;
    this.desc = desc;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.gid = gid;
    builder.name = name;
    builder.desc = desc;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBGroup)) return false;
    PBGroup o = (PBGroup) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(gid, o.gid)
        && Internal.equals(name, o.name)
        && Internal.equals(desc, o.desc);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (gid != null ? gid.hashCode() : 0);
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (desc != null ? desc.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (gid != null) builder.append(", gid=").append(gid);
    if (name != null) builder.append(", name=").append(name);
    if (desc != null) builder.append(", desc=").append(desc);
    return builder.replace(0, 2, "PBGroup{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBGroup, Builder> {
    public Long gid;

    public String name;

    public String desc;

    public Builder() {
    }

    /**
     * 	???id
     */
    public Builder gid(Long gid) {
      this.gid = gid;
      return this;
    }

    /**
     * 	?????
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * 	???????
     */
    public Builder desc(String desc) {
      this.desc = desc;
      return this;
    }

    @Override
    public PBGroup build() {
      if (gid == null) {
        throw Internal.missingRequiredFields(gid, "gid");
      }
      return new PBGroup(gid, name, desc, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBGroup extends ProtoAdapter<PBGroup> {
    ProtoAdapter_PBGroup() {
      super(FieldEncoding.LENGTH_DELIMITED, PBGroup.class);
    }

    @Override
    public int encodedSize(PBGroup value) {
      return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.gid)
          + (value.name != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.name) : 0)
          + (value.desc != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.desc) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBGroup value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.gid);
      if (value.name != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name);
      if (value.desc != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.desc);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBGroup decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.gid(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.desc(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBGroup redact(PBGroup value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
