// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 145:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBGroupAddMemberRsp extends Message<PBGroupAddMemberRsp, PBGroupAddMemberRsp.Builder> {
  public static final ProtoAdapter<PBGroupAddMemberRsp> ADAPTER = new ProtoAdapter_PBGroupAddMemberRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  public PBGroupAddMemberRsp(Integer result) {
    this(result, ByteString.EMPTY);
  }

  public PBGroupAddMemberRsp(Integer result, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBGroupAddMemberRsp)) return false;
    PBGroupAddMemberRsp o = (PBGroupAddMemberRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    return builder.replace(0, 2, "PBGroupAddMemberRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBGroupAddMemberRsp, Builder> {
    public Integer result;

    public Builder() {
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    @Override
    public PBGroupAddMemberRsp build() {
      return new PBGroupAddMemberRsp(result, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBGroupAddMemberRsp extends ProtoAdapter<PBGroupAddMemberRsp> {
    ProtoAdapter_PBGroupAddMemberRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBGroupAddMemberRsp.class);
    }

    @Override
    public int encodedSize(PBGroupAddMemberRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBGroupAddMemberRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBGroupAddMemberRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBGroupAddMemberRsp redact(PBGroupAddMemberRsp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
