// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 104:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBGroupFilter extends Message<PBGroupFilter, PBGroupFilter.Builder> {
  public static final ProtoAdapter<PBGroupFilter> ADAPTER = new ProtoAdapter_PBGroupFilter();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_NAME = 0;

  public static final Integer DEFAULT_DESC = 0;

  public static final Integer DEFAULT_MEMBER = 0;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer name;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer desc;

  @WireField(
      tag = 11,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer member;

  public PBGroupFilter(Integer name, Integer desc, Integer member) {
    this(name, desc, member, ByteString.EMPTY);
  }

  public PBGroupFilter(Integer name, Integer desc, Integer member, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.name = name;
    this.desc = desc;
    this.member = member;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.name = name;
    builder.desc = desc;
    builder.member = member;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBGroupFilter)) return false;
    PBGroupFilter o = (PBGroupFilter) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(name, o.name)
        && Internal.equals(desc, o.desc)
        && Internal.equals(member, o.member);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (desc != null ? desc.hashCode() : 0);
      result = result * 37 + (member != null ? member.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (name != null) builder.append(", name=").append(name);
    if (desc != null) builder.append(", desc=").append(desc);
    if (member != null) builder.append(", member=").append(member);
    return builder.replace(0, 2, "PBGroupFilter{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBGroupFilter, Builder> {
    public Integer name;

    public Integer desc;

    public Integer member;

    public Builder() {
    }

    public Builder name(Integer name) {
      this.name = name;
      return this;
    }

    public Builder desc(Integer desc) {
      this.desc = desc;
      return this;
    }

    public Builder member(Integer member) {
      this.member = member;
      return this;
    }

    @Override
    public PBGroupFilter build() {
      return new PBGroupFilter(name, desc, member, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBGroupFilter extends ProtoAdapter<PBGroupFilter> {
    ProtoAdapter_PBGroupFilter() {
      super(FieldEncoding.LENGTH_DELIMITED, PBGroupFilter.class);
    }

    @Override
    public int encodedSize(PBGroupFilter value) {
      return (value.name != null ? ProtoAdapter.INT32.encodedSizeWithTag(2, value.name) : 0)
          + (value.desc != null ? ProtoAdapter.INT32.encodedSizeWithTag(3, value.desc) : 0)
          + (value.member != null ? ProtoAdapter.INT32.encodedSizeWithTag(11, value.member) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBGroupFilter value) throws IOException {
      if (value.name != null) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.name);
      if (value.desc != null) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.desc);
      if (value.member != null) ProtoAdapter.INT32.encodeWithTag(writer, 11, value.member);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBGroupFilter decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 2: builder.name(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.desc(ProtoAdapter.INT32.decode(reader)); break;
          case 11: builder.member(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBGroupFilter redact(PBGroupFilter value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
