// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 131:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ???????
 */
public final class PBGroupDestroyReq extends Message<PBGroupDestroyReq, PBGroupDestroyReq.Builder> {
  public static final ProtoAdapter<PBGroupDestroyReq> ADAPTER = new ProtoAdapter_PBGroupDestroyReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_GID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long gid;

  public PBGroupDestroyReq(Long gid) {
    this(gid, ByteString.EMPTY);
  }

  public PBGroupDestroyReq(Long gid, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.gid = gid;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.gid = gid;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBGroupDestroyReq)) return false;
    PBGroupDestroyReq o = (PBGroupDestroyReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(gid, o.gid);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (gid != null ? gid.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (gid != null) builder.append(", gid=").append(gid);
    return builder.replace(0, 2, "PBGroupDestroyReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBGroupDestroyReq, Builder> {
    public Long gid;

    public Builder() {
    }

    public Builder gid(Long gid) {
      this.gid = gid;
      return this;
    }

    @Override
    public PBGroupDestroyReq build() {
      if (gid == null) {
        throw Internal.missingRequiredFields(gid, "gid");
      }
      return new PBGroupDestroyReq(gid, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBGroupDestroyReq extends ProtoAdapter<PBGroupDestroyReq> {
    ProtoAdapter_PBGroupDestroyReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBGroupDestroyReq.class);
    }

    @Override
    public int encodedSize(PBGroupDestroyReq value) {
      return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.gid)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBGroupDestroyReq value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.gid);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBGroupDestroyReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.gid(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBGroupDestroyReq redact(PBGroupDestroyReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
