// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 202:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * im��Ϣͬ��(app����ʱӦ��ͬ��IM���������ݴ����Ϣ)
 */
public final class PBImSyncReq extends Message<PBImSyncReq, PBImSyncReq.Builder> {
  public static final ProtoAdapter<PBImSyncReq> ADAPTER = new ProtoAdapter_PBImSyncReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_START_IMSGID = 0L;

  public static final Integer DEFAULT_COUNT = 0;

  /**
   * 	ͬ����ʼ����Ϣid��
   */
  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long start_imsgid;

  /**
   * 	���ͬ������Ϣ��������Сֵ1�����ֵ200��������Ϊ100
   */
  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer count;

  public PBImSyncReq(Long start_imsgid, Integer count) {
    this(start_imsgid, count, ByteString.EMPTY);
  }

  public PBImSyncReq(Long start_imsgid, Integer count, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.start_imsgid = start_imsgid;
    this.count = count;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.start_imsgid = start_imsgid;
    builder.count = count;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBImSyncReq)) return false;
    PBImSyncReq o = (PBImSyncReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(start_imsgid, o.start_imsgid)
        && Internal.equals(count, o.count);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (start_imsgid != null ? start_imsgid.hashCode() : 0);
      result = result * 37 + (count != null ? count.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (start_imsgid != null) builder.append(", start_imsgid=").append(start_imsgid);
    if (count != null) builder.append(", count=").append(count);
    return builder.replace(0, 2, "PBImSyncReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBImSyncReq, Builder> {
    public Long start_imsgid;

    public Integer count;

    public Builder() {
    }

    /**
     * 	ͬ����ʼ����Ϣid��
     */
    public Builder start_imsgid(Long start_imsgid) {
      this.start_imsgid = start_imsgid;
      return this;
    }

    /**
     * 	���ͬ������Ϣ��������Сֵ1�����ֵ200��������Ϊ100
     */
    public Builder count(Integer count) {
      this.count = count;
      return this;
    }

    @Override
    public PBImSyncReq build() {
      return new PBImSyncReq(start_imsgid, count, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBImSyncReq extends ProtoAdapter<PBImSyncReq> {
    ProtoAdapter_PBImSyncReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBImSyncReq.class);
    }

    @Override
    public int encodedSize(PBImSyncReq value) {
      return (value.start_imsgid != null ? ProtoAdapter.UINT64.encodedSizeWithTag(6, value.start_imsgid) : 0)
          + (value.count != null ? ProtoAdapter.UINT32.encodedSizeWithTag(7, value.count) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBImSyncReq value) throws IOException {
      if (value.start_imsgid != null) ProtoAdapter.UINT64.encodeWithTag(writer, 6, value.start_imsgid);
      if (value.count != null) ProtoAdapter.UINT32.encodeWithTag(writer, 7, value.count);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBImSyncReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 6: builder.start_imsgid(ProtoAdapter.UINT64.decode(reader)); break;
          case 7: builder.count(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBImSyncReq redact(PBImSyncReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
