// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 215:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * im��Ϣ����
 */
public final class PBImPostReq extends Message<PBImPostReq, PBImPostReq.Builder> {
  public static final ProtoAdapter<PBImPostReq> ADAPTER = new ProtoAdapter_PBImPostReq();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 6,
      adapter = "org.yeewoe.mopanet.protos.PBImMsg#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final PBImMsg imsg;

  public PBImPostReq(PBImMsg imsg) {
    this(imsg, ByteString.EMPTY);
  }

  public PBImPostReq(PBImMsg imsg, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.imsg = imsg;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.imsg = imsg;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBImPostReq)) return false;
    PBImPostReq o = (PBImPostReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(imsg, o.imsg);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (imsg != null ? imsg.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (imsg != null) builder.append(", imsg=").append(imsg);
    return builder.replace(0, 2, "PBImPostReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBImPostReq, Builder> {
    public PBImMsg imsg;

    public Builder() {
    }

    public Builder imsg(PBImMsg imsg) {
      this.imsg = imsg;
      return this;
    }

    @Override
    public PBImPostReq build() {
      if (imsg == null) {
        throw Internal.missingRequiredFields(imsg, "imsg");
      }
      return new PBImPostReq(imsg, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBImPostReq extends ProtoAdapter<PBImPostReq> {
    ProtoAdapter_PBImPostReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBImPostReq.class);
    }

    @Override
    public int encodedSize(PBImPostReq value) {
      return PBImMsg.ADAPTER.encodedSizeWithTag(6, value.imsg)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBImPostReq value) throws IOException {
      PBImMsg.ADAPTER.encodeWithTag(writer, 6, value.imsg);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBImPostReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 6: builder.imsg(PBImMsg.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBImPostReq redact(PBImPostReq value) {
      Builder builder = value.newBuilder();
      if (builder.imsg != null) builder.imsg = PBImMsg.ADAPTER.redact(builder.imsg);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
