// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 176:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * ////////////////////////////////////////////////////////
 */
public enum PBImMsgContentType implements WireEnum {
  IMCT_TEXT(0),

  IMCT_VOICE(1),

  IMCT_IMAGE(2);

  public static final ProtoAdapter<PBImMsgContentType> ADAPTER = ProtoAdapter.newEnumAdapter(PBImMsgContentType.class);

  private final int value;

  PBImMsgContentType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static PBImMsgContentType fromValue(int value) {
    switch (value) {
      case 0: return IMCT_TEXT;
      case 1: return IMCT_VOICE;
      case 2: return IMCT_IMAGE;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
