// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 182:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum PBImMsgClass implements WireEnum {
  /**
   * 	������Ϣ
   */
  IMCLSS_U2U(0),

  /**
   * 	Ⱥ����Ϣ
   */
  IMCLSS_U2G(1);

  public static final ProtoAdapter<PBImMsgClass> ADAPTER = ProtoAdapter.newEnumAdapter(PBImMsgClass.class);

  private final int value;

  PBImMsgClass(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static PBImMsgClass fromValue(int value) {
    switch (value) {
      case 0: return IMCLSS_U2U;
      case 1: return IMCLSS_U2G;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
