// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 207:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class PBImSyncRsp extends Message<PBImSyncRsp, PBImSyncRsp.Builder> {
  public static final ProtoAdapter<PBImSyncRsp> ADAPTER = new ProtoAdapter_PBImSyncRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  public static final Long DEFAULT_NEXT_IMSGID = 0L;

  /**
   * 	��Ϊ0��ʾ����
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  /**
   * 	���ص���Ϣ�б�
   */
  @WireField(
      tag = 2,
      adapter = "org.yeewoe.mopanet.protos.PBImMsg#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<PBImMsg> imsgs;

  /**
   * 	���ֵ�����ã���ʾ���������Ϣ��������Ӧ�ü�������PBImu2uSyncReq���󣬰�PBImu2uSyncReq.start_imsgid����Ϊ��ֵ
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long next_imsgid;

  public PBImSyncRsp(Integer result, List<PBImMsg> imsgs, Long next_imsgid) {
    this(result, imsgs, next_imsgid, ByteString.EMPTY);
  }

  public PBImSyncRsp(Integer result, List<PBImMsg> imsgs, Long next_imsgid, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.imsgs = Internal.immutableCopyOf("imsgs", imsgs);
    this.next_imsgid = next_imsgid;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.imsgs = Internal.copyOf("imsgs", imsgs);
    builder.next_imsgid = next_imsgid;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBImSyncRsp)) return false;
    PBImSyncRsp o = (PBImSyncRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(imsgs, o.imsgs)
        && Internal.equals(next_imsgid, o.next_imsgid);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (imsgs != null ? imsgs.hashCode() : 1);
      result_ = result_ * 37 + (next_imsgid != null ? next_imsgid.hashCode() : 0);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (imsgs != null) builder.append(", imsgs=").append(imsgs);
    if (next_imsgid != null) builder.append(", next_imsgid=").append(next_imsgid);
    return builder.replace(0, 2, "PBImSyncRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBImSyncRsp, Builder> {
    public Integer result;

    public List<PBImMsg> imsgs;

    public Long next_imsgid;

    public Builder() {
      imsgs = Internal.newMutableList();
    }

    /**
     * 	��Ϊ0��ʾ����
     */
    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 	���ص���Ϣ�б�
     */
    public Builder imsgs(List<PBImMsg> imsgs) {
      Internal.checkElementsNotNull(imsgs);
      this.imsgs = imsgs;
      return this;
    }

    /**
     * 	���ֵ�����ã���ʾ���������Ϣ��������Ӧ�ü�������PBImu2uSyncReq���󣬰�PBImu2uSyncReq.start_imsgid����Ϊ��ֵ
     */
    public Builder next_imsgid(Long next_imsgid) {
      this.next_imsgid = next_imsgid;
      return this;
    }

    @Override
    public PBImSyncRsp build() {
      return new PBImSyncRsp(result, imsgs, next_imsgid, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBImSyncRsp extends ProtoAdapter<PBImSyncRsp> {
    ProtoAdapter_PBImSyncRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBImSyncRsp.class);
    }

    @Override
    public int encodedSize(PBImSyncRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + PBImMsg.ADAPTER.asRepeated().encodedSizeWithTag(2, value.imsgs)
          + (value.next_imsgid != null ? ProtoAdapter.UINT64.encodedSizeWithTag(3, value.next_imsgid) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBImSyncRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.imsgs != null) PBImMsg.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.imsgs);
      if (value.next_imsgid != null) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.next_imsgid);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBImSyncRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.imsgs.add(PBImMsg.ADAPTER.decode(reader)); break;
          case 3: builder.next_imsgid(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBImSyncRsp redact(PBImSyncRsp value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.imsgs, PBImMsg.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
