// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 187:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBImMsg extends Message<PBImMsg, PBImMsg.Builder> {
  public static final ProtoAdapter<PBImMsg> ADAPTER = new ProtoAdapter_PBImMsg();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_IMSGID = 0L;

  public static final Integer DEFAULT_IMSGCTYPE = 0;

  public static final ByteString DEFAULT_IMSG = ByteString.EMPTY;

  public static final Long DEFAULT_IMSGTIME = 0L;

  public static final Integer DEFAULT_IMCLASS = 0;

  public static final Long DEFAULT_FROM_UID = 0L;

  public static final Long DEFAULT_FROM_GID = 0L;

  public static final Long DEFAULT_TO_UID = 0L;

  public static final Long DEFAULT_TO_GID = 0L;

  /**
   * 	��ϢID
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long imsgid;

  /**
   * 	��Ϣ�������ͣ�ȡֵΪPBImMsgContentָ��
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer imsgctype;

  /**
   * 	��Ϣ����
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES",
      label = WireField.Label.REQUIRED
  )
  public final ByteString imsg;

  /**
   * 	��Ϣ�ִ��������ʱ��
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long imsgtime;

  /**
   * 	��Ϣ��,ȡֵΪPBImMsgClassָ��
   */
  @WireField(
      tag = 10,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer imclass;

  /**
   * 	��Ϣ�����ߣ����ˣ�
   */
  @WireField(
      tag = 11,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long from_uid;

  /**
   * 	��Ϣ�����ߣ�Ⱥ�飩
   */
  @WireField(
      tag = 12,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long from_gid;

  /**
   * 	��Ϣ�����ߣ����ˣ�
   */
  @WireField(
      tag = 13,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long to_uid;

  /**
   * 	��Ϣ�����ߣ�Ⱥ�飩
   */
  @WireField(
      tag = 14,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long to_gid;

  public PBImMsg(Long imsgid, Integer imsgctype, ByteString imsg, Long imsgtime, Integer imclass, Long from_uid, Long from_gid, Long to_uid, Long to_gid) {
    this(imsgid, imsgctype, imsg, imsgtime, imclass, from_uid, from_gid, to_uid, to_gid, ByteString.EMPTY);
  }

  public PBImMsg(Long imsgid, Integer imsgctype, ByteString imsg, Long imsgtime, Integer imclass, Long from_uid, Long from_gid, Long to_uid, Long to_gid, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.imsgid = imsgid;
    this.imsgctype = imsgctype;
    this.imsg = imsg;
    this.imsgtime = imsgtime;
    this.imclass = imclass;
    this.from_uid = from_uid;
    this.from_gid = from_gid;
    this.to_uid = to_uid;
    this.to_gid = to_gid;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.imsgid = imsgid;
    builder.imsgctype = imsgctype;
    builder.imsg = imsg;
    builder.imsgtime = imsgtime;
    builder.imclass = imclass;
    builder.from_uid = from_uid;
    builder.from_gid = from_gid;
    builder.to_uid = to_uid;
    builder.to_gid = to_gid;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBImMsg)) return false;
    PBImMsg o = (PBImMsg) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(imsgid, o.imsgid)
        && Internal.equals(imsgctype, o.imsgctype)
        && Internal.equals(imsg, o.imsg)
        && Internal.equals(imsgtime, o.imsgtime)
        && Internal.equals(imclass, o.imclass)
        && Internal.equals(from_uid, o.from_uid)
        && Internal.equals(from_gid, o.from_gid)
        && Internal.equals(to_uid, o.to_uid)
        && Internal.equals(to_gid, o.to_gid);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (imsgid != null ? imsgid.hashCode() : 0);
      result = result * 37 + (imsgctype != null ? imsgctype.hashCode() : 0);
      result = result * 37 + (imsg != null ? imsg.hashCode() : 0);
      result = result * 37 + (imsgtime != null ? imsgtime.hashCode() : 0);
      result = result * 37 + (imclass != null ? imclass.hashCode() : 0);
      result = result * 37 + (from_uid != null ? from_uid.hashCode() : 0);
      result = result * 37 + (from_gid != null ? from_gid.hashCode() : 0);
      result = result * 37 + (to_uid != null ? to_uid.hashCode() : 0);
      result = result * 37 + (to_gid != null ? to_gid.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (imsgid != null) builder.append(", imsgid=").append(imsgid);
    if (imsgctype != null) builder.append(", imsgctype=").append(imsgctype);
    if (imsg != null) builder.append(", imsg=").append(imsg);
    if (imsgtime != null) builder.append(", imsgtime=").append(imsgtime);
    if (imclass != null) builder.append(", imclass=").append(imclass);
    if (from_uid != null) builder.append(", from_uid=").append(from_uid);
    if (from_gid != null) builder.append(", from_gid=").append(from_gid);
    if (to_uid != null) builder.append(", to_uid=").append(to_uid);
    if (to_gid != null) builder.append(", to_gid=").append(to_gid);
    return builder.replace(0, 2, "PBImMsg{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBImMsg, Builder> {
    public Long imsgid;

    public Integer imsgctype;

    public ByteString imsg;

    public Long imsgtime;

    public Integer imclass;

    public Long from_uid;

    public Long from_gid;

    public Long to_uid;

    public Long to_gid;

    public Builder() {
    }

    /**
     * 	��ϢID
     */
    public Builder imsgid(Long imsgid) {
      this.imsgid = imsgid;
      return this;
    }

    /**
     * 	��Ϣ�������ͣ�ȡֵΪPBImMsgContentָ��
     */
    public Builder imsgctype(Integer imsgctype) {
      this.imsgctype = imsgctype;
      return this;
    }

    /**
     * 	��Ϣ����
     */
    public Builder imsg(ByteString imsg) {
      this.imsg = imsg;
      return this;
    }

    /**
     * 	��Ϣ�ִ��������ʱ��
     */
    public Builder imsgtime(Long imsgtime) {
      this.imsgtime = imsgtime;
      return this;
    }

    /**
     * 	��Ϣ��,ȡֵΪPBImMsgClassָ��
     */
    public Builder imclass(Integer imclass) {
      this.imclass = imclass;
      return this;
    }

    /**
     * 	��Ϣ�����ߣ����ˣ�
     */
    public Builder from_uid(Long from_uid) {
      this.from_uid = from_uid;
      return this;
    }

    /**
     * 	��Ϣ�����ߣ�Ⱥ�飩
     */
    public Builder from_gid(Long from_gid) {
      this.from_gid = from_gid;
      return this;
    }

    /**
     * 	��Ϣ�����ߣ����ˣ�
     */
    public Builder to_uid(Long to_uid) {
      this.to_uid = to_uid;
      return this;
    }

    /**
     * 	��Ϣ�����ߣ�Ⱥ�飩
     */
    public Builder to_gid(Long to_gid) {
      this.to_gid = to_gid;
      return this;
    }

    @Override
    public PBImMsg build() {
      if (imsgid == null
          || imsg == null) {
        throw Internal.missingRequiredFields(imsgid, "imsgid",
            imsg, "imsg");
      }
      return new PBImMsg(imsgid, imsgctype, imsg, imsgtime, imclass, from_uid, from_gid, to_uid, to_gid, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBImMsg extends ProtoAdapter<PBImMsg> {
    ProtoAdapter_PBImMsg() {
      super(FieldEncoding.LENGTH_DELIMITED, PBImMsg.class);
    }

    @Override
    public int encodedSize(PBImMsg value) {
      return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.imsgid)
          + (value.imsgctype != null ? ProtoAdapter.INT32.encodedSizeWithTag(2, value.imsgctype) : 0)
          + ProtoAdapter.BYTES.encodedSizeWithTag(3, value.imsg)
          + (value.imsgtime != null ? ProtoAdapter.UINT64.encodedSizeWithTag(4, value.imsgtime) : 0)
          + (value.imclass != null ? ProtoAdapter.UINT32.encodedSizeWithTag(10, value.imclass) : 0)
          + (value.from_uid != null ? ProtoAdapter.UINT64.encodedSizeWithTag(11, value.from_uid) : 0)
          + (value.from_gid != null ? ProtoAdapter.UINT64.encodedSizeWithTag(12, value.from_gid) : 0)
          + (value.to_uid != null ? ProtoAdapter.UINT64.encodedSizeWithTag(13, value.to_uid) : 0)
          + (value.to_gid != null ? ProtoAdapter.UINT64.encodedSizeWithTag(14, value.to_gid) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBImMsg value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.imsgid);
      if (value.imsgctype != null) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.imsgctype);
      ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.imsg);
      if (value.imsgtime != null) ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.imsgtime);
      if (value.imclass != null) ProtoAdapter.UINT32.encodeWithTag(writer, 10, value.imclass);
      if (value.from_uid != null) ProtoAdapter.UINT64.encodeWithTag(writer, 11, value.from_uid);
      if (value.from_gid != null) ProtoAdapter.UINT64.encodeWithTag(writer, 12, value.from_gid);
      if (value.to_uid != null) ProtoAdapter.UINT64.encodeWithTag(writer, 13, value.to_uid);
      if (value.to_gid != null) ProtoAdapter.UINT64.encodeWithTag(writer, 14, value.to_gid);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBImMsg decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.imsgid(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.imsgctype(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.imsg(ProtoAdapter.BYTES.decode(reader)); break;
          case 4: builder.imsgtime(ProtoAdapter.UINT64.decode(reader)); break;
          case 10: builder.imclass(ProtoAdapter.UINT32.decode(reader)); break;
          case 11: builder.from_uid(ProtoAdapter.UINT64.decode(reader)); break;
          case 12: builder.from_gid(ProtoAdapter.UINT64.decode(reader)); break;
          case 13: builder.to_uid(ProtoAdapter.UINT64.decode(reader)); break;
          case 14: builder.to_gid(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBImMsg redact(PBImMsg value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
