// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 240:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ??????????
 */
public final class PBLocNearUserReq extends Message<PBLocNearUserReq, PBLocNearUserReq.Builder> {
  public static final ProtoAdapter<PBLocNearUserReq> ADAPTER = new ProtoAdapter_PBLocNearUserReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_MIN_DISTANCE = 0L;

  public static final Long DEFAULT_MAX_DISTANCE = 0L;

  public static final Long DEFAULT_ACTIVE_TIMEOUT = 0L;

  public static final Integer DEFAULT_NUM = 0;

  /**
   * 	?????
   */
  @WireField(
      tag = 1,
      adapter = "org.yeewoe.mopanet.protos.PBMapPostion#ADAPTER"
  )
  public final PBMapPostion center_loc;

  /**
   * 	????????????��??
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long min_distance;

  /**
   * 	????????????��??
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long max_distance;

  /**
   * 	?????????????��?????????????????????active_timeout???????
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long active_timeout;

  /**
   * optional	uint32			skip = 5;			//	????????????
   * 	???????????
   */
  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer num;

  public PBLocNearUserReq(PBMapPostion center_loc, Long min_distance, Long max_distance, Long active_timeout, Integer num) {
    this(center_loc, min_distance, max_distance, active_timeout, num, ByteString.EMPTY);
  }

  public PBLocNearUserReq(PBMapPostion center_loc, Long min_distance, Long max_distance, Long active_timeout, Integer num, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.center_loc = center_loc;
    this.min_distance = min_distance;
    this.max_distance = max_distance;
    this.active_timeout = active_timeout;
    this.num = num;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.center_loc = center_loc;
    builder.min_distance = min_distance;
    builder.max_distance = max_distance;
    builder.active_timeout = active_timeout;
    builder.num = num;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBLocNearUserReq)) return false;
    PBLocNearUserReq o = (PBLocNearUserReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(center_loc, o.center_loc)
        && Internal.equals(min_distance, o.min_distance)
        && Internal.equals(max_distance, o.max_distance)
        && Internal.equals(active_timeout, o.active_timeout)
        && Internal.equals(num, o.num);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (center_loc != null ? center_loc.hashCode() : 0);
      result = result * 37 + (min_distance != null ? min_distance.hashCode() : 0);
      result = result * 37 + (max_distance != null ? max_distance.hashCode() : 0);
      result = result * 37 + (active_timeout != null ? active_timeout.hashCode() : 0);
      result = result * 37 + (num != null ? num.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (center_loc != null) builder.append(", center_loc=").append(center_loc);
    if (min_distance != null) builder.append(", min_distance=").append(min_distance);
    if (max_distance != null) builder.append(", max_distance=").append(max_distance);
    if (active_timeout != null) builder.append(", active_timeout=").append(active_timeout);
    if (num != null) builder.append(", num=").append(num);
    return builder.replace(0, 2, "PBLocNearUserReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBLocNearUserReq, Builder> {
    public PBMapPostion center_loc;

    public Long min_distance;

    public Long max_distance;

    public Long active_timeout;

    public Integer num;

    public Builder() {
    }

    /**
     * 	?????
     */
    public Builder center_loc(PBMapPostion center_loc) {
      this.center_loc = center_loc;
      return this;
    }

    /**
     * 	????????????��??
     */
    public Builder min_distance(Long min_distance) {
      this.min_distance = min_distance;
      return this;
    }

    /**
     * 	????????????��??
     */
    public Builder max_distance(Long max_distance) {
      this.max_distance = max_distance;
      return this;
    }

    /**
     * 	?????????????��?????????????????????active_timeout???????
     */
    public Builder active_timeout(Long active_timeout) {
      this.active_timeout = active_timeout;
      return this;
    }

    /**
     * optional	uint32			skip = 5;			//	????????????
     * 	???????????
     */
    public Builder num(Integer num) {
      this.num = num;
      return this;
    }

    @Override
    public PBLocNearUserReq build() {
      return new PBLocNearUserReq(center_loc, min_distance, max_distance, active_timeout, num, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBLocNearUserReq extends ProtoAdapter<PBLocNearUserReq> {
    ProtoAdapter_PBLocNearUserReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBLocNearUserReq.class);
    }

    @Override
    public int encodedSize(PBLocNearUserReq value) {
      return (value.center_loc != null ? PBMapPostion.ADAPTER.encodedSizeWithTag(1, value.center_loc) : 0)
          + (value.min_distance != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.min_distance) : 0)
          + (value.max_distance != null ? ProtoAdapter.UINT64.encodedSizeWithTag(3, value.max_distance) : 0)
          + (value.active_timeout != null ? ProtoAdapter.UINT64.encodedSizeWithTag(4, value.active_timeout) : 0)
          + (value.num != null ? ProtoAdapter.UINT32.encodedSizeWithTag(6, value.num) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBLocNearUserReq value) throws IOException {
      if (value.center_loc != null) PBMapPostion.ADAPTER.encodeWithTag(writer, 1, value.center_loc);
      if (value.min_distance != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.min_distance);
      if (value.max_distance != null) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.max_distance);
      if (value.active_timeout != null) ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.active_timeout);
      if (value.num != null) ProtoAdapter.UINT32.encodeWithTag(writer, 6, value.num);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBLocNearUserReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.center_loc(PBMapPostion.ADAPTER.decode(reader)); break;
          case 2: builder.min_distance(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.max_distance(ProtoAdapter.UINT64.decode(reader)); break;
          case 4: builder.active_timeout(ProtoAdapter.UINT64.decode(reader)); break;
          case 6: builder.num(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBLocNearUserReq redact(PBLocNearUserReq value) {
      Builder builder = value.newBuilder();
      if (builder.center_loc != null) builder.center_loc = PBMapPostion.ADAPTER.redact(builder.center_loc);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
