// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 256:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class PBLocNearUserRsp extends Message<PBLocNearUserRsp, PBLocNearUserRsp.Builder> {
  public static final ProtoAdapter<PBLocNearUserRsp> ADAPTER = new ProtoAdapter_PBLocNearUserRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  /**
   * 	????????????��?
   */
  @WireField(
      tag = 2,
      adapter = "org.yeewoe.mopanet.protos.PBLocUser#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<PBLocUser> users;

  public PBLocNearUserRsp(Integer result, List<PBLocUser> users) {
    this(result, users, ByteString.EMPTY);
  }

  public PBLocNearUserRsp(Integer result, List<PBLocUser> users, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.users = Internal.immutableCopyOf("users", users);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.users = Internal.copyOf("users", users);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBLocNearUserRsp)) return false;
    PBLocNearUserRsp o = (PBLocNearUserRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(users, o.users);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (users != null ? users.hashCode() : 1);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (users != null) builder.append(", users=").append(users);
    return builder.replace(0, 2, "PBLocNearUserRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBLocNearUserRsp, Builder> {
    public Integer result;

    public List<PBLocUser> users;

    public Builder() {
      users = Internal.newMutableList();
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 	????????????��?
     */
    public Builder users(List<PBLocUser> users) {
      Internal.checkElementsNotNull(users);
      this.users = users;
      return this;
    }

    @Override
    public PBLocNearUserRsp build() {
      return new PBLocNearUserRsp(result, users, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBLocNearUserRsp extends ProtoAdapter<PBLocNearUserRsp> {
    ProtoAdapter_PBLocNearUserRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBLocNearUserRsp.class);
    }

    @Override
    public int encodedSize(PBLocNearUserRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + PBLocUser.ADAPTER.asRepeated().encodedSizeWithTag(2, value.users)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBLocNearUserRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.users != null) PBLocUser.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.users);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBLocNearUserRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.users.add(PBLocUser.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBLocNearUserRsp redact(PBLocNearUserRsp value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.users, PBLocUser.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
