// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 249:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Double;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBLocUser extends Message<PBLocUser, PBLocUser.Builder> {
  public static final ProtoAdapter<PBLocUser> ADAPTER = new ProtoAdapter_PBLocUser();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_UID = 0L;

  public static final Long DEFAULT_ATIME = 0L;

  public static final Double DEFAULT_DIST = 0.0d;

  /**
   * 	???
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long uid;

  /**
   * 	??????????��??
   */
  @WireField(
      tag = 2,
      adapter = "org.yeewoe.mopanet.protos.PBMapPostion#ADAPTER"
  )
  public final PBMapPostion loc;

  /**
   * 	??????????��??????
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long atime;

  /**
   * 	??????��??
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  public final Double dist;

  public PBLocUser(Long uid, PBMapPostion loc, Long atime, Double dist) {
    this(uid, loc, atime, dist, ByteString.EMPTY);
  }

  public PBLocUser(Long uid, PBMapPostion loc, Long atime, Double dist, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.uid = uid;
    this.loc = loc;
    this.atime = atime;
    this.dist = dist;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.uid = uid;
    builder.loc = loc;
    builder.atime = atime;
    builder.dist = dist;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBLocUser)) return false;
    PBLocUser o = (PBLocUser) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(uid, o.uid)
        && Internal.equals(loc, o.loc)
        && Internal.equals(atime, o.atime)
        && Internal.equals(dist, o.dist);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (uid != null ? uid.hashCode() : 0);
      result = result * 37 + (loc != null ? loc.hashCode() : 0);
      result = result * 37 + (atime != null ? atime.hashCode() : 0);
      result = result * 37 + (dist != null ? dist.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (uid != null) builder.append(", uid=").append(uid);
    if (loc != null) builder.append(", loc=").append(loc);
    if (atime != null) builder.append(", atime=").append(atime);
    if (dist != null) builder.append(", dist=").append(dist);
    return builder.replace(0, 2, "PBLocUser{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBLocUser, Builder> {
    public Long uid;

    public PBMapPostion loc;

    public Long atime;

    public Double dist;

    public Builder() {
    }

    /**
     * 	???
     */
    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    /**
     * 	??????????��??
     */
    public Builder loc(PBMapPostion loc) {
      this.loc = loc;
      return this;
    }

    /**
     * 	??????????��??????
     */
    public Builder atime(Long atime) {
      this.atime = atime;
      return this;
    }

    /**
     * 	??????��??
     */
    public Builder dist(Double dist) {
      this.dist = dist;
      return this;
    }

    @Override
    public PBLocUser build() {
      if (uid == null) {
        throw Internal.missingRequiredFields(uid, "uid");
      }
      return new PBLocUser(uid, loc, atime, dist, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBLocUser extends ProtoAdapter<PBLocUser> {
    ProtoAdapter_PBLocUser() {
      super(FieldEncoding.LENGTH_DELIMITED, PBLocUser.class);
    }

    @Override
    public int encodedSize(PBLocUser value) {
      return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.uid)
          + (value.loc != null ? PBMapPostion.ADAPTER.encodedSizeWithTag(2, value.loc) : 0)
          + (value.atime != null ? ProtoAdapter.UINT64.encodedSizeWithTag(3, value.atime) : 0)
          + (value.dist != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(4, value.dist) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBLocUser value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.uid);
      if (value.loc != null) PBMapPostion.ADAPTER.encodeWithTag(writer, 2, value.loc);
      if (value.atime != null) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.atime);
      if (value.dist != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 4, value.dist);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBLocUser decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.uid(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.loc(PBMapPostion.ADAPTER.decode(reader)); break;
          case 3: builder.atime(ProtoAdapter.UINT64.decode(reader)); break;
          case 4: builder.dist(ProtoAdapter.DOUBLE.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBLocUser redact(PBLocUser value) {
      Builder builder = value.newBuilder();
      if (builder.loc != null) builder.loc = PBMapPostion.ADAPTER.redact(builder.loc);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
