// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 230:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ???????��??
 */
public final class PBLocReportReq extends Message<PBLocReportReq, PBLocReportReq.Builder> {
  public static final ProtoAdapter<PBLocReportReq> ADAPTER = new ProtoAdapter_PBLocReportReq();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "org.yeewoe.mopanet.protos.PBMapPostion#ADAPTER"
  )
  public final PBMapPostion loc;

  public PBLocReportReq(PBMapPostion loc) {
    this(loc, ByteString.EMPTY);
  }

  public PBLocReportReq(PBMapPostion loc, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.loc = loc;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.loc = loc;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBLocReportReq)) return false;
    PBLocReportReq o = (PBLocReportReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(loc, o.loc);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (loc != null ? loc.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (loc != null) builder.append(", loc=").append(loc);
    return builder.replace(0, 2, "PBLocReportReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBLocReportReq, Builder> {
    public PBMapPostion loc;

    public Builder() {
    }

    public Builder loc(PBMapPostion loc) {
      this.loc = loc;
      return this;
    }

    @Override
    public PBLocReportReq build() {
      return new PBLocReportReq(loc, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBLocReportReq extends ProtoAdapter<PBLocReportReq> {
    ProtoAdapter_PBLocReportReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBLocReportReq.class);
    }

    @Override
    public int encodedSize(PBLocReportReq value) {
      return (value.loc != null ? PBMapPostion.ADAPTER.encodedSizeWithTag(1, value.loc) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBLocReportReq value) throws IOException {
      if (value.loc != null) PBMapPostion.ADAPTER.encodeWithTag(writer, 1, value.loc);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBLocReportReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.loc(PBMapPostion.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBLocReportReq redact(PBLocReportReq value) {
      Builder builder = value.newBuilder();
      if (builder.loc != null) builder.loc = PBMapPostion.ADAPTER.redact(builder.loc);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
