// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 278:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBMDbgHelp extends Message<PBMDbgHelp, PBMDbgHelp.Builder> {
  public static final ProtoAdapter<PBMDbgHelp> ADAPTER = new ProtoAdapter_PBMDbgHelp();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_CMDNAME = "";

  public static final String DEFAULT_CMDHELP = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String cmdname;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String cmdhelp;

  public PBMDbgHelp(String cmdname, String cmdhelp) {
    this(cmdname, cmdhelp, ByteString.EMPTY);
  }

  public PBMDbgHelp(String cmdname, String cmdhelp, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.cmdname = cmdname;
    this.cmdhelp = cmdhelp;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.cmdname = cmdname;
    builder.cmdhelp = cmdhelp;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBMDbgHelp)) return false;
    PBMDbgHelp o = (PBMDbgHelp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(cmdname, o.cmdname)
        && Internal.equals(cmdhelp, o.cmdhelp);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (cmdname != null ? cmdname.hashCode() : 0);
      result = result * 37 + (cmdhelp != null ? cmdhelp.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (cmdname != null) builder.append(", cmdname=").append(cmdname);
    if (cmdhelp != null) builder.append(", cmdhelp=").append(cmdhelp);
    return builder.replace(0, 2, "PBMDbgHelp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBMDbgHelp, Builder> {
    public String cmdname;

    public String cmdhelp;

    public Builder() {
    }

    public Builder cmdname(String cmdname) {
      this.cmdname = cmdname;
      return this;
    }

    public Builder cmdhelp(String cmdhelp) {
      this.cmdhelp = cmdhelp;
      return this;
    }

    @Override
    public PBMDbgHelp build() {
      if (cmdname == null
          || cmdhelp == null) {
        throw Internal.missingRequiredFields(cmdname, "cmdname",
            cmdhelp, "cmdhelp");
      }
      return new PBMDbgHelp(cmdname, cmdhelp, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBMDbgHelp extends ProtoAdapter<PBMDbgHelp> {
    ProtoAdapter_PBMDbgHelp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBMDbgHelp.class);
    }

    @Override
    public int encodedSize(PBMDbgHelp value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.cmdname)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.cmdhelp)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBMDbgHelp value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.cmdname);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.cmdhelp);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBMDbgHelp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.cmdname(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.cmdhelp(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBMDbgHelp redact(PBMDbgHelp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
