// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 4:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * ?????????
 */
public enum PBMediaType implements WireEnum {
  /**
   * 	???
   */
  PBMT_TXT(0),

  /**
   * 	??
   */
  PBMT_IMAGE(1),

  /**
   * 	????
   */
  PBMT_VOICE(2),

  /**
   * 	???
   */
  PBMT_VIDEO(3),

  /**
   * 	??????
   */
  PBMT_HYPERLINK(4);

  public static final ProtoAdapter<PBMediaType> ADAPTER = ProtoAdapter.newEnumAdapter(PBMediaType.class);

  private final int value;

  PBMediaType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static PBMediaType fromValue(int value) {
    switch (value) {
      case 0: return PBMT_TXT;
      case 1: return PBMT_IMAGE;
      case 2: return PBMT_VOICE;
      case 3: return PBMT_VIDEO;
      case 4: return PBMT_HYPERLINK;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
