// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 299:2
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class PBMProxyRsp extends Message<PBMProxyRsp, PBMProxyRsp.Builder> {
  public static final ProtoAdapter<PBMProxyRsp> ADAPTER = new ProtoAdapter_PBMProxyRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  /**
   * 	��Ӧ�б�
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES",
      label = WireField.Label.REPEATED
  )
  public final List<ByteString> rsps;

  public PBMProxyRsp(Integer result, List<ByteString> rsps) {
    this(result, rsps, ByteString.EMPTY);
  }

  public PBMProxyRsp(Integer result, List<ByteString> rsps, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.rsps = Internal.immutableCopyOf("rsps", rsps);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.rsps = Internal.copyOf("rsps", rsps);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBMProxyRsp)) return false;
    PBMProxyRsp o = (PBMProxyRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(rsps, o.rsps);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (rsps != null ? rsps.hashCode() : 1);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (rsps != null) builder.append(", rsps=").append(rsps);
    return builder.replace(0, 2, "PBMProxyRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBMProxyRsp, Builder> {
    public Integer result;

    public List<ByteString> rsps;

    public Builder() {
      rsps = Internal.newMutableList();
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 	��Ӧ�б�
     */
    public Builder rsps(List<ByteString> rsps) {
      Internal.checkElementsNotNull(rsps);
      this.rsps = rsps;
      return this;
    }

    @Override
    public PBMProxyRsp build() {
      return new PBMProxyRsp(result, rsps, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBMProxyRsp extends ProtoAdapter<PBMProxyRsp> {
    ProtoAdapter_PBMProxyRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBMProxyRsp.class);
    }

    @Override
    public int encodedSize(PBMProxyRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + ProtoAdapter.BYTES.asRepeated().encodedSizeWithTag(2, value.rsps)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBMProxyRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.rsps != null) ProtoAdapter.BYTES.asRepeated().encodeWithTag(writer, 2, value.rsps);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBMProxyRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.rsps.add(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBMProxyRsp redact(PBMProxyRsp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
