// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 295:2
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * �ϲ���������
 */
public final class PBMProxyReq extends Message<PBMProxyReq, PBMProxyReq.Builder> {
  public static final ProtoAdapter<PBMProxyReq> ADAPTER = new ProtoAdapter_PBMProxyReq();

  private static final long serialVersionUID = 0L;

  /**
   * 	�����б� ע�⣺��¼��֤�������ܷ�������
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES",
      label = WireField.Label.REPEATED
  )
  public final List<ByteString> reqs;

  public PBMProxyReq(List<ByteString> reqs) {
    this(reqs, ByteString.EMPTY);
  }

  public PBMProxyReq(List<ByteString> reqs, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.reqs = Internal.immutableCopyOf("reqs", reqs);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.reqs = Internal.copyOf("reqs", reqs);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBMProxyReq)) return false;
    PBMProxyReq o = (PBMProxyReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(reqs, o.reqs);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (reqs != null ? reqs.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (reqs != null) builder.append(", reqs=").append(reqs);
    return builder.replace(0, 2, "PBMProxyReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBMProxyReq, Builder> {
    public List<ByteString> reqs;

    public Builder() {
      reqs = Internal.newMutableList();
    }

    /**
     * 	�����б� ע�⣺��¼��֤�������ܷ�������
     */
    public Builder reqs(List<ByteString> reqs) {
      Internal.checkElementsNotNull(reqs);
      this.reqs = reqs;
      return this;
    }

    @Override
    public PBMProxyReq build() {
      return new PBMProxyReq(reqs, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBMProxyReq extends ProtoAdapter<PBMProxyReq> {
    ProtoAdapter_PBMProxyReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBMProxyReq.class);
    }

    @Override
    public int encodedSize(PBMProxyReq value) {
      return ProtoAdapter.BYTES.asRepeated().encodedSizeWithTag(1, value.reqs)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBMProxyReq value) throws IOException {
      if (value.reqs != null) ProtoAdapter.BYTES.asRepeated().encodeWithTag(writer, 1, value.reqs);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBMProxyReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.reqs.add(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBMProxyReq redact(PBMProxyReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
