// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 313:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBRoute extends Message<PBRoute, PBRoute.Builder> {
  public static final ProtoAdapter<PBRoute> ADAPTER = new ProtoAdapter_PBRoute();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_SRVOP = 0;

  public static final Long DEFAULT_FLAG = 0L;

  public static final Integer DEFAULT_ERR_NO = 0;

  public static final Long DEFAULT_TO_GID = 0L;

  public static final Long DEFAULT_TO_UID = 0L;

  public static final Long DEFAULT_FROM_GID = 0L;

  public static final Long DEFAULT_FROM_UID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer srvop;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long flag;

  @WireField(
      tag = 3,
      adapter = "org.yeewoe.mopanet.protos.PBModInfo#ADAPTER"
  )
  public final PBModInfo modinfo;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer err_no;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long to_gid;

  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long to_uid;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long from_gid;

  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long from_uid;

  public PBRoute(Integer srvop, Long flag, PBModInfo modinfo, Integer err_no, Long to_gid, Long to_uid, Long from_gid, Long from_uid) {
    this(srvop, flag, modinfo, err_no, to_gid, to_uid, from_gid, from_uid, ByteString.EMPTY);
  }

  public PBRoute(Integer srvop, Long flag, PBModInfo modinfo, Integer err_no, Long to_gid, Long to_uid, Long from_gid, Long from_uid, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.srvop = srvop;
    this.flag = flag;
    this.modinfo = modinfo;
    this.err_no = err_no;
    this.to_gid = to_gid;
    this.to_uid = to_uid;
    this.from_gid = from_gid;
    this.from_uid = from_uid;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.srvop = srvop;
    builder.flag = flag;
    builder.modinfo = modinfo;
    builder.err_no = err_no;
    builder.to_gid = to_gid;
    builder.to_uid = to_uid;
    builder.from_gid = from_gid;
    builder.from_uid = from_uid;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBRoute)) return false;
    PBRoute o = (PBRoute) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(srvop, o.srvop)
        && Internal.equals(flag, o.flag)
        && Internal.equals(modinfo, o.modinfo)
        && Internal.equals(err_no, o.err_no)
        && Internal.equals(to_gid, o.to_gid)
        && Internal.equals(to_uid, o.to_uid)
        && Internal.equals(from_gid, o.from_gid)
        && Internal.equals(from_uid, o.from_uid);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (srvop != null ? srvop.hashCode() : 0);
      result = result * 37 + (flag != null ? flag.hashCode() : 0);
      result = result * 37 + (modinfo != null ? modinfo.hashCode() : 0);
      result = result * 37 + (err_no != null ? err_no.hashCode() : 0);
      result = result * 37 + (to_gid != null ? to_gid.hashCode() : 0);
      result = result * 37 + (to_uid != null ? to_uid.hashCode() : 0);
      result = result * 37 + (from_gid != null ? from_gid.hashCode() : 0);
      result = result * 37 + (from_uid != null ? from_uid.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (srvop != null) builder.append(", srvop=").append(srvop);
    if (flag != null) builder.append(", flag=").append(flag);
    if (modinfo != null) builder.append(", modinfo=").append(modinfo);
    if (err_no != null) builder.append(", err_no=").append(err_no);
    if (to_gid != null) builder.append(", to_gid=").append(to_gid);
    if (to_uid != null) builder.append(", to_uid=").append(to_uid);
    if (from_gid != null) builder.append(", from_gid=").append(from_gid);
    if (from_uid != null) builder.append(", from_uid=").append(from_uid);
    return builder.replace(0, 2, "PBRoute{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBRoute, Builder> {
    public Integer srvop;

    public Long flag;

    public PBModInfo modinfo;

    public Integer err_no;

    public Long to_gid;

    public Long to_uid;

    public Long from_gid;

    public Long from_uid;

    public Builder() {
    }

    public Builder srvop(Integer srvop) {
      this.srvop = srvop;
      return this;
    }

    public Builder flag(Long flag) {
      this.flag = flag;
      return this;
    }

    public Builder modinfo(PBModInfo modinfo) {
      this.modinfo = modinfo;
      return this;
    }

    public Builder err_no(Integer err_no) {
      this.err_no = err_no;
      return this;
    }

    public Builder to_gid(Long to_gid) {
      this.to_gid = to_gid;
      return this;
    }

    public Builder to_uid(Long to_uid) {
      this.to_uid = to_uid;
      return this;
    }

    public Builder from_gid(Long from_gid) {
      this.from_gid = from_gid;
      return this;
    }

    public Builder from_uid(Long from_uid) {
      this.from_uid = from_uid;
      return this;
    }

    @Override
    public PBRoute build() {
      if (srvop == null) {
        throw Internal.missingRequiredFields(srvop, "srvop");
      }
      return new PBRoute(srvop, flag, modinfo, err_no, to_gid, to_uid, from_gid, from_uid, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBRoute extends ProtoAdapter<PBRoute> {
    ProtoAdapter_PBRoute() {
      super(FieldEncoding.LENGTH_DELIMITED, PBRoute.class);
    }

    @Override
    public int encodedSize(PBRoute value) {
      return ProtoAdapter.UINT32.encodedSizeWithTag(1, value.srvop)
          + (value.flag != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.flag) : 0)
          + (value.modinfo != null ? PBModInfo.ADAPTER.encodedSizeWithTag(3, value.modinfo) : 0)
          + (value.err_no != null ? ProtoAdapter.INT32.encodedSizeWithTag(4, value.err_no) : 0)
          + (value.to_gid != null ? ProtoAdapter.INT64.encodedSizeWithTag(6, value.to_gid) : 0)
          + (value.to_uid != null ? ProtoAdapter.INT64.encodedSizeWithTag(7, value.to_uid) : 0)
          + (value.from_gid != null ? ProtoAdapter.INT64.encodedSizeWithTag(8, value.from_gid) : 0)
          + (value.from_uid != null ? ProtoAdapter.INT64.encodedSizeWithTag(9, value.from_uid) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBRoute value) throws IOException {
      ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.srvop);
      if (value.flag != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.flag);
      if (value.modinfo != null) PBModInfo.ADAPTER.encodeWithTag(writer, 3, value.modinfo);
      if (value.err_no != null) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.err_no);
      if (value.to_gid != null) ProtoAdapter.INT64.encodeWithTag(writer, 6, value.to_gid);
      if (value.to_uid != null) ProtoAdapter.INT64.encodeWithTag(writer, 7, value.to_uid);
      if (value.from_gid != null) ProtoAdapter.INT64.encodeWithTag(writer, 8, value.from_gid);
      if (value.from_uid != null) ProtoAdapter.INT64.encodeWithTag(writer, 9, value.from_uid);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBRoute decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.srvop(ProtoAdapter.UINT32.decode(reader)); break;
          case 2: builder.flag(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.modinfo(PBModInfo.ADAPTER.decode(reader)); break;
          case 4: builder.err_no(ProtoAdapter.INT32.decode(reader)); break;
          case 6: builder.to_gid(ProtoAdapter.INT64.decode(reader)); break;
          case 7: builder.to_uid(ProtoAdapter.INT64.decode(reader)); break;
          case 8: builder.from_gid(ProtoAdapter.INT64.decode(reader)); break;
          case 9: builder.from_uid(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBRoute redact(PBRoute value) {
      Builder builder = value.newBuilder();
      if (builder.modinfo != null) builder.modinfo = PBModInfo.ADAPTER.redact(builder.modinfo);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
