// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 397:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ��ȡָ���û��Ķ�̬�б�
 */
public final class PBTrdPullUserReq extends Message<PBTrdPullUserReq, PBTrdPullUserReq.Builder> {
  public static final ProtoAdapter<PBTrdPullUserReq> ADAPTER = new ProtoAdapter_PBTrdPullUserReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_UID = 0L;

  public static final Long DEFAULT_START_ID = 0L;

  public static final Long DEFAULT_COUNT = 0L;

  public static final Integer DEFAULT_PURPOSE = 0;

  /**
   * 	ָ���û�
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long uid;

  /**
   * 	��̬��ʼ��id��������������µĿ�ʼ
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long start_id;

  /**
   * 	������ȡ�Ķ�̬������С1�����1000��Ĭ��20��  ��ע�⣺��̬id�ǴӴ���С���Ƶģ�
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long count;

  /**
   * ��̬��Ŀ��
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer purpose;

  public PBTrdPullUserReq(Long uid, Long start_id, Long count, Integer purpose) {
    this(uid, start_id, count, purpose, ByteString.EMPTY);
  }

  public PBTrdPullUserReq(Long uid, Long start_id, Long count, Integer purpose, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.uid = uid;
    this.start_id = start_id;
    this.count = count;
    this.purpose = purpose;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.uid = uid;
    builder.start_id = start_id;
    builder.count = count;
    builder.purpose = purpose;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBTrdPullUserReq)) return false;
    PBTrdPullUserReq o = (PBTrdPullUserReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(uid, o.uid)
        && Internal.equals(start_id, o.start_id)
        && Internal.equals(count, o.count)
        && Internal.equals(purpose, o.purpose);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (uid != null ? uid.hashCode() : 0);
      result = result * 37 + (start_id != null ? start_id.hashCode() : 0);
      result = result * 37 + (count != null ? count.hashCode() : 0);
      result = result * 37 + (purpose != null ? purpose.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (uid != null) builder.append(", uid=").append(uid);
    if (start_id != null) builder.append(", start_id=").append(start_id);
    if (count != null) builder.append(", count=").append(count);
    if (purpose != null) builder.append(", purpose=").append(purpose);
    return builder.replace(0, 2, "PBTrdPullUserReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBTrdPullUserReq, Builder> {
    public Long uid;

    public Long start_id;

    public Long count;

    public Integer purpose;

    public Builder() {
    }

    /**
     * 	ָ���û�
     */
    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    /**
     * 	��̬��ʼ��id��������������µĿ�ʼ
     */
    public Builder start_id(Long start_id) {
      this.start_id = start_id;
      return this;
    }

    /**
     * 	������ȡ�Ķ�̬������С1�����1000��Ĭ��20��  ��ע�⣺��̬id�ǴӴ���С���Ƶģ�
     */
    public Builder count(Long count) {
      this.count = count;
      return this;
    }

    /**
     * ��̬��Ŀ��
     */
    public Builder purpose(Integer purpose) {
      this.purpose = purpose;
      return this;
    }

    @Override
    public PBTrdPullUserReq build() {
      return new PBTrdPullUserReq(uid, start_id, count, purpose, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBTrdPullUserReq extends ProtoAdapter<PBTrdPullUserReq> {
    ProtoAdapter_PBTrdPullUserReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBTrdPullUserReq.class);
    }

    @Override
    public int encodedSize(PBTrdPullUserReq value) {
      return (value.uid != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.uid) : 0)
          + (value.start_id != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.start_id) : 0)
          + (value.count != null ? ProtoAdapter.UINT64.encodedSizeWithTag(3, value.count) : 0)
          + (value.purpose != null ? ProtoAdapter.INT32.encodedSizeWithTag(5, value.purpose) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBTrdPullUserReq value) throws IOException {
      if (value.uid != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.uid);
      if (value.start_id != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.start_id);
      if (value.count != null) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.count);
      if (value.purpose != null) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.purpose);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBTrdPullUserReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.uid(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.start_id(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.count(ProtoAdapter.UINT64.decode(reader)); break;
          case 5: builder.purpose(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBTrdPullUserReq redact(PBTrdPullUserReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
