// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 455:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ����
 */
public final class PBTrdLikeReq extends Message<PBTrdLikeReq, PBTrdLikeReq.Builder> {
  public static final ProtoAdapter<PBTrdLikeReq> ADAPTER = new ProtoAdapter_PBTrdLikeReq();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_LIKE = 0;

  public static final Long DEFAULT_ID = 0L;

  public static final Long DEFAULT_UID = 0L;

  /**
   * 0��ϲ����1ϲ��
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer like;

  /**
   * ϲ����ϲ����trend id
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long id;

  /**
   * �����û�id
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long uid;

  public PBTrdLikeReq(Integer like, Long id, Long uid) {
    this(like, id, uid, ByteString.EMPTY);
  }

  public PBTrdLikeReq(Integer like, Long id, Long uid, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.like = like;
    this.id = id;
    this.uid = uid;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.like = like;
    builder.id = id;
    builder.uid = uid;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBTrdLikeReq)) return false;
    PBTrdLikeReq o = (PBTrdLikeReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(like, o.like)
        && Internal.equals(id, o.id)
        && Internal.equals(uid, o.uid);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (like != null ? like.hashCode() : 0);
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (uid != null ? uid.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (like != null) builder.append(", like=").append(like);
    if (id != null) builder.append(", id=").append(id);
    if (uid != null) builder.append(", uid=").append(uid);
    return builder.replace(0, 2, "PBTrdLikeReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBTrdLikeReq, Builder> {
    public Integer like;

    public Long id;

    public Long uid;

    public Builder() {
    }

    /**
     * 0��ϲ����1ϲ��
     */
    public Builder like(Integer like) {
      this.like = like;
      return this;
    }

    /**
     * ϲ����ϲ����trend id
     */
    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    /**
     * �����û�id
     */
    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    @Override
    public PBTrdLikeReq build() {
      return new PBTrdLikeReq(like, id, uid, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBTrdLikeReq extends ProtoAdapter<PBTrdLikeReq> {
    ProtoAdapter_PBTrdLikeReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBTrdLikeReq.class);
    }

    @Override
    public int encodedSize(PBTrdLikeReq value) {
      return (value.like != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.like) : 0)
          + (value.id != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.id) : 0)
          + (value.uid != null ? ProtoAdapter.UINT64.encodedSizeWithTag(3, value.uid) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBTrdLikeReq value) throws IOException {
      if (value.like != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.like);
      if (value.id != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.id);
      if (value.uid != null) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.uid);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBTrdLikeReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.like(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.id(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.uid(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBTrdLikeReq redact(PBTrdLikeReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
