// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 340:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * ��̬��Ŀ��
 */
public enum PBTrendsPurpose implements WireEnum {
  /**
   * men for women
   */
  TRDP_M4W(1),

  /**
   * mem for men
   */
  TRDP_M4M(2),

  /**
   * womem for man
   */
  TRDP_W4M(3),

  /**
   * woman for women
   */
  TRDP_W4W(4),

  /**
   * ALL
   */
  TRDP_ALL(5);

  public static final ProtoAdapter<PBTrendsPurpose> ADAPTER = ProtoAdapter.newEnumAdapter(PBTrendsPurpose.class);

  private final int value;

  PBTrendsPurpose(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static PBTrendsPurpose fromValue(int value) {
    switch (value) {
      case 1: return TRDP_M4W;
      case 2: return TRDP_M4M;
      case 3: return TRDP_W4M;
      case 4: return TRDP_W4W;
      case 5: return TRDP_ALL;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
