// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 365:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ������̬
 */
public final class PBTrdAddReq extends Message<PBTrdAddReq, PBTrdAddReq.Builder> {
  public static final ProtoAdapter<PBTrdAddReq> ADAPTER = new ProtoAdapter_PBTrdAddReq();

  private static final long serialVersionUID = 0L;

  /**
   * 	��̬����
   */
  @WireField(
      tag = 1,
      adapter = "org.yeewoe.mopanet.protos.PBTrends#ADAPTER"
  )
  public final PBTrends trend;

  public PBTrdAddReq(PBTrends trend) {
    this(trend, ByteString.EMPTY);
  }

  public PBTrdAddReq(PBTrends trend, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.trend = trend;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.trend = trend;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBTrdAddReq)) return false;
    PBTrdAddReq o = (PBTrdAddReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(trend, o.trend);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (trend != null ? trend.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (trend != null) builder.append(", trend=").append(trend);
    return builder.replace(0, 2, "PBTrdAddReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBTrdAddReq, Builder> {
    public PBTrends trend;

    public Builder() {
    }

    /**
     * 	��̬����
     */
    public Builder trend(PBTrends trend) {
      this.trend = trend;
      return this;
    }

    @Override
    public PBTrdAddReq build() {
      return new PBTrdAddReq(trend, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBTrdAddReq extends ProtoAdapter<PBTrdAddReq> {
    ProtoAdapter_PBTrdAddReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBTrdAddReq.class);
    }

    @Override
    public int encodedSize(PBTrdAddReq value) {
      return (value.trend != null ? PBTrends.ADAPTER.encodedSizeWithTag(1, value.trend) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBTrdAddReq value) throws IOException {
      if (value.trend != null) PBTrends.ADAPTER.encodeWithTag(writer, 1, value.trend);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBTrdAddReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.trend(PBTrends.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBTrdAddReq redact(PBTrdAddReq value) {
      Builder builder = value.newBuilder();
      if (builder.trend != null) builder.trend = PBTrends.ADAPTER.redact(builder.trend);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
