// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 332:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * ��̬
 * ��̬�ɼ���
 */
public enum PBTrendsView implements WireEnum {
  /**
   * 	����
   */
  TRDV_PUBLIC(1),

  /**
   * 	�����ѿɼ�
   */
  TRDV_FRIEND(3),

  /**
   * 	ֻ�Լ��ɼ�
   */
  TRDV_SELF(5);

  public static final ProtoAdapter<PBTrendsView> ADAPTER = ProtoAdapter.newEnumAdapter(PBTrendsView.class);

  private final int value;

  PBTrendsView(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static PBTrendsView fromValue(int value) {
    switch (value) {
      case 1: return TRDV_PUBLIC;
      case 3: return TRDV_FRIEND;
      case 5: return TRDV_SELF;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
