// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 425:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * ��ȡ�û��б�ÿ���û������������̬
 */
public final class PBTrdListUserLastReq extends Message<PBTrdListUserLastReq, PBTrdListUserLastReq.Builder> {
  public static final ProtoAdapter<PBTrdListUserLastReq> ADAPTER = new ProtoAdapter_PBTrdListUserLastReq();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_PURPOSE = 0;

  /**
   * 	�û��б�
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REPEATED
  )
  public final List<Long> uids;

  /**
   * ��̬��Ŀ��
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer purpose;

  public PBTrdListUserLastReq(List<Long> uids, Integer purpose) {
    this(uids, purpose, ByteString.EMPTY);
  }

  public PBTrdListUserLastReq(List<Long> uids, Integer purpose, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.uids = Internal.immutableCopyOf("uids", uids);
    this.purpose = purpose;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.uids = Internal.copyOf("uids", uids);
    builder.purpose = purpose;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBTrdListUserLastReq)) return false;
    PBTrdListUserLastReq o = (PBTrdListUserLastReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(uids, o.uids)
        && Internal.equals(purpose, o.purpose);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (uids != null ? uids.hashCode() : 1);
      result = result * 37 + (purpose != null ? purpose.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (uids != null) builder.append(", uids=").append(uids);
    if (purpose != null) builder.append(", purpose=").append(purpose);
    return builder.replace(0, 2, "PBTrdListUserLastReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBTrdListUserLastReq, Builder> {
    public List<Long> uids;

    public Integer purpose;

    public Builder() {
      uids = Internal.newMutableList();
    }

    /**
     * 	�û��б�
     */
    public Builder uids(List<Long> uids) {
      Internal.checkElementsNotNull(uids);
      this.uids = uids;
      return this;
    }

    /**
     * ��̬��Ŀ��
     */
    public Builder purpose(Integer purpose) {
      this.purpose = purpose;
      return this;
    }

    @Override
    public PBTrdListUserLastReq build() {
      return new PBTrdListUserLastReq(uids, purpose, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBTrdListUserLastReq extends ProtoAdapter<PBTrdListUserLastReq> {
    ProtoAdapter_PBTrdListUserLastReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBTrdListUserLastReq.class);
    }

    @Override
    public int encodedSize(PBTrdListUserLastReq value) {
      return ProtoAdapter.UINT64.asRepeated().encodedSizeWithTag(1, value.uids)
          + (value.purpose != null ? ProtoAdapter.INT32.encodedSizeWithTag(5, value.purpose) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBTrdListUserLastReq value) throws IOException {
      if (value.uids != null) ProtoAdapter.UINT64.asRepeated().encodeWithTag(writer, 1, value.uids);
      if (value.purpose != null) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.purpose);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBTrdListUserLastReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.uids.add(ProtoAdapter.UINT64.decode(reader)); break;
          case 5: builder.purpose(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBTrdListUserLastReq redact(PBTrdListUserLastReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
