// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 369:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBTrdAddRsp extends Message<PBTrdAddRsp, PBTrdAddRsp.Builder> {
  public static final ProtoAdapter<PBTrdAddRsp> ADAPTER = new ProtoAdapter_PBTrdAddRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  public static final Long DEFAULT_ID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  /**
   * 	���ض�̬id
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long id;

  public PBTrdAddRsp(Integer result, Long id) {
    this(result, id, ByteString.EMPTY);
  }

  public PBTrdAddRsp(Integer result, Long id, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.id = id;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.id = id;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBTrdAddRsp)) return false;
    PBTrdAddRsp o = (PBTrdAddRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(id, o.id);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (id != null ? id.hashCode() : 0);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (id != null) builder.append(", id=").append(id);
    return builder.replace(0, 2, "PBTrdAddRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBTrdAddRsp, Builder> {
    public Integer result;

    public Long id;

    public Builder() {
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 	���ض�̬id
     */
    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    @Override
    public PBTrdAddRsp build() {
      return new PBTrdAddRsp(result, id, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBTrdAddRsp extends ProtoAdapter<PBTrdAddRsp> {
    ProtoAdapter_PBTrdAddRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBTrdAddRsp.class);
    }

    @Override
    public int encodedSize(PBTrdAddRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + (value.id != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.id) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBTrdAddRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.id != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.id);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBTrdAddRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.id(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBTrdAddRsp redact(PBTrdAddRsp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
