// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 549:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * ������ȡ�û�
 */
public final class PBUsrBatchGetReq extends Message<PBUsrBatchGetReq, PBUsrBatchGetReq.Builder> {
  public static final ProtoAdapter<PBUsrBatchGetReq> ADAPTER = new ProtoAdapter_PBUsrBatchGetReq();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "org.yeewoe.mopanet.protos.PBUserFilter#ADAPTER"
  )
  public final PBUserFilter filter;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REPEATED
  )
  public final List<Long> uids;

  public PBUsrBatchGetReq(PBUserFilter filter, List<Long> uids) {
    this(filter, uids, ByteString.EMPTY);
  }

  public PBUsrBatchGetReq(PBUserFilter filter, List<Long> uids, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.filter = filter;
    this.uids = Internal.immutableCopyOf("uids", uids);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.filter = filter;
    builder.uids = Internal.copyOf("uids", uids);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrBatchGetReq)) return false;
    PBUsrBatchGetReq o = (PBUsrBatchGetReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(filter, o.filter)
        && Internal.equals(uids, o.uids);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (filter != null ? filter.hashCode() : 0);
      result = result * 37 + (uids != null ? uids.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (filter != null) builder.append(", filter=").append(filter);
    if (uids != null) builder.append(", uids=").append(uids);
    return builder.replace(0, 2, "PBUsrBatchGetReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrBatchGetReq, Builder> {
    public PBUserFilter filter;

    public List<Long> uids;

    public Builder() {
      uids = Internal.newMutableList();
    }

    public Builder filter(PBUserFilter filter) {
      this.filter = filter;
      return this;
    }

    public Builder uids(List<Long> uids) {
      Internal.checkElementsNotNull(uids);
      this.uids = uids;
      return this;
    }

    @Override
    public PBUsrBatchGetReq build() {
      return new PBUsrBatchGetReq(filter, uids, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrBatchGetReq extends ProtoAdapter<PBUsrBatchGetReq> {
    ProtoAdapter_PBUsrBatchGetReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrBatchGetReq.class);
    }

    @Override
    public int encodedSize(PBUsrBatchGetReq value) {
      return (value.filter != null ? PBUserFilter.ADAPTER.encodedSizeWithTag(1, value.filter) : 0)
          + ProtoAdapter.UINT64.asRepeated().encodedSizeWithTag(2, value.uids)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrBatchGetReq value) throws IOException {
      if (value.filter != null) PBUserFilter.ADAPTER.encodeWithTag(writer, 1, value.filter);
      if (value.uids != null) ProtoAdapter.UINT64.asRepeated().encodeWithTag(writer, 2, value.uids);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrBatchGetReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.filter(PBUserFilter.ADAPTER.decode(reader)); break;
          case 2: builder.uids.add(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrBatchGetReq redact(PBUsrBatchGetReq value) {
      Builder builder = value.newBuilder();
      if (builder.filter != null) builder.filter = PBUserFilter.ADAPTER.redact(builder.filter);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
