// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 638:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ������
 */
public final class PBUsrKickoutPush extends Message<PBUsrKickoutPush, PBUsrKickoutPush.Builder> {
  public static final ProtoAdapter<PBUsrKickoutPush> ADAPTER = new ProtoAdapter_PBUsrKickoutPush();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_REASON = 0;

  /**
   * 	����ԭ��
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer reason;

  public PBUsrKickoutPush(Integer reason) {
    this(reason, ByteString.EMPTY);
  }

  public PBUsrKickoutPush(Integer reason, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.reason = reason;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.reason = reason;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrKickoutPush)) return false;
    PBUsrKickoutPush o = (PBUsrKickoutPush) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(reason, o.reason);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (reason != null ? reason.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (reason != null) builder.append(", reason=").append(reason);
    return builder.replace(0, 2, "PBUsrKickoutPush{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrKickoutPush, Builder> {
    public Integer reason;

    public Builder() {
    }

    /**
     * 	����ԭ��
     */
    public Builder reason(Integer reason) {
      this.reason = reason;
      return this;
    }

    @Override
    public PBUsrKickoutPush build() {
      if (reason == null) {
        throw Internal.missingRequiredFields(reason, "reason");
      }
      return new PBUsrKickoutPush(reason, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrKickoutPush extends ProtoAdapter<PBUsrKickoutPush> {
    ProtoAdapter_PBUsrKickoutPush() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrKickoutPush.class);
    }

    @Override
    public int encodedSize(PBUsrKickoutPush value) {
      return ProtoAdapter.INT32.encodedSizeWithTag(1, value.reason)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrKickoutPush value) throws IOException {
      ProtoAdapter.INT32.encodeWithTag(writer, 1, value.reason);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrKickoutPush decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.reason(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrKickoutPush redact(PBUsrKickoutPush value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
