// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 526:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * �޸��û�
 */
public final class PBUsrSetReq extends Message<PBUsrSetReq, PBUsrSetReq.Builder> {
  public static final ProtoAdapter<PBUsrSetReq> ADAPTER = new ProtoAdapter_PBUsrSetReq();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "org.yeewoe.mopanet.protos.PBUserFilter#ADAPTER"
  )
  public final PBUserFilter filter;

  @WireField(
      tag = 2,
      adapter = "org.yeewoe.mopanet.protos.PBUser#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final PBUser user;

  public PBUsrSetReq(PBUserFilter filter, PBUser user) {
    this(filter, user, ByteString.EMPTY);
  }

  public PBUsrSetReq(PBUserFilter filter, PBUser user, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.filter = filter;
    this.user = user;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.filter = filter;
    builder.user = user;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrSetReq)) return false;
    PBUsrSetReq o = (PBUsrSetReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(filter, o.filter)
        && Internal.equals(user, o.user);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (filter != null ? filter.hashCode() : 0);
      result = result * 37 + (user != null ? user.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (filter != null) builder.append(", filter=").append(filter);
    if (user != null) builder.append(", user=").append(user);
    return builder.replace(0, 2, "PBUsrSetReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrSetReq, Builder> {
    public PBUserFilter filter;

    public PBUser user;

    public Builder() {
    }

    public Builder filter(PBUserFilter filter) {
      this.filter = filter;
      return this;
    }

    public Builder user(PBUser user) {
      this.user = user;
      return this;
    }

    @Override
    public PBUsrSetReq build() {
      if (user == null) {
        throw Internal.missingRequiredFields(user, "user");
      }
      return new PBUsrSetReq(filter, user, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrSetReq extends ProtoAdapter<PBUsrSetReq> {
    ProtoAdapter_PBUsrSetReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrSetReq.class);
    }

    @Override
    public int encodedSize(PBUsrSetReq value) {
      return (value.filter != null ? PBUserFilter.ADAPTER.encodedSizeWithTag(1, value.filter) : 0)
          + PBUser.ADAPTER.encodedSizeWithTag(2, value.user)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrSetReq value) throws IOException {
      if (value.filter != null) PBUserFilter.ADAPTER.encodeWithTag(writer, 1, value.filter);
      PBUser.ADAPTER.encodeWithTag(writer, 2, value.user);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrSetReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.filter(PBUserFilter.ADAPTER.decode(reader)); break;
          case 2: builder.user(PBUser.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrSetReq redact(PBUsrSetReq value) {
      Builder builder = value.newBuilder();
      if (builder.filter != null) builder.filter = PBUserFilter.ADAPTER.redact(builder.filter);
      if (builder.user != null) builder.user = PBUser.ADAPTER.redact(builder.user);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
