// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 650:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class PBUsrFollowReq extends Message<PBUsrFollowReq, PBUsrFollowReq.Builder> {
  public static final ProtoAdapter<PBUsrFollowReq> ADAPTER = new ProtoAdapter_PBUsrFollowReq();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_OP = 0;

  /**
   * 	��ע������ȡֵΪPBUsrFollowOp
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer op;

  /**
   * 	�����û��б�
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REPEATED
  )
  public final List<Long> uids;

  public PBUsrFollowReq(Integer op, List<Long> uids) {
    this(op, uids, ByteString.EMPTY);
  }

  public PBUsrFollowReq(Integer op, List<Long> uids, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.op = op;
    this.uids = Internal.immutableCopyOf("uids", uids);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.op = op;
    builder.uids = Internal.copyOf("uids", uids);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrFollowReq)) return false;
    PBUsrFollowReq o = (PBUsrFollowReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(op, o.op)
        && Internal.equals(uids, o.uids);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (op != null ? op.hashCode() : 0);
      result = result * 37 + (uids != null ? uids.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (op != null) builder.append(", op=").append(op);
    if (uids != null) builder.append(", uids=").append(uids);
    return builder.replace(0, 2, "PBUsrFollowReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrFollowReq, Builder> {
    public Integer op;

    public List<Long> uids;

    public Builder() {
      uids = Internal.newMutableList();
    }

    /**
     * 	��ע������ȡֵΪPBUsrFollowOp
     */
    public Builder op(Integer op) {
      this.op = op;
      return this;
    }

    /**
     * 	�����û��б�
     */
    public Builder uids(List<Long> uids) {
      Internal.checkElementsNotNull(uids);
      this.uids = uids;
      return this;
    }

    @Override
    public PBUsrFollowReq build() {
      return new PBUsrFollowReq(op, uids, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrFollowReq extends ProtoAdapter<PBUsrFollowReq> {
    ProtoAdapter_PBUsrFollowReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrFollowReq.class);
    }

    @Override
    public int encodedSize(PBUsrFollowReq value) {
      return (value.op != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.op) : 0)
          + ProtoAdapter.UINT64.asRepeated().encodedSizeWithTag(2, value.uids)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrFollowReq value) throws IOException {
      if (value.op != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.op);
      if (value.uids != null) ProtoAdapter.UINT64.asRepeated().encodeWithTag(writer, 2, value.uids);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrFollowReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.op(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.uids.add(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrFollowReq redact(PBUsrFollowReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
