// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 505:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * �����û�
 */
public final class PBUsrCreateReq extends Message<PBUsrCreateReq, PBUsrCreateReq.Builder> {
  public static final ProtoAdapter<PBUsrCreateReq> ADAPTER = new ProtoAdapter_PBUsrCreateReq();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "org.yeewoe.mopanet.protos.PBUser#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<PBUser> users;

  public PBUsrCreateReq(List<PBUser> users) {
    this(users, ByteString.EMPTY);
  }

  public PBUsrCreateReq(List<PBUser> users, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.users = Internal.immutableCopyOf("users", users);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.users = Internal.copyOf("users", users);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrCreateReq)) return false;
    PBUsrCreateReq o = (PBUsrCreateReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(users, o.users);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (users != null ? users.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (users != null) builder.append(", users=").append(users);
    return builder.replace(0, 2, "PBUsrCreateReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrCreateReq, Builder> {
    public List<PBUser> users;

    public Builder() {
      users = Internal.newMutableList();
    }

    public Builder users(List<PBUser> users) {
      Internal.checkElementsNotNull(users);
      this.users = users;
      return this;
    }

    @Override
    public PBUsrCreateReq build() {
      return new PBUsrCreateReq(users, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrCreateReq extends ProtoAdapter<PBUsrCreateReq> {
    ProtoAdapter_PBUsrCreateReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrCreateReq.class);
    }

    @Override
    public int encodedSize(PBUsrCreateReq value) {
      return PBUser.ADAPTER.asRepeated().encodedSizeWithTag(1, value.users)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrCreateReq value) throws IOException {
      if (value.users != null) PBUser.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.users);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrCreateReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.users.add(PBUser.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrCreateReq redact(PBUsrCreateReq value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.users, PBUser.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
