// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 537:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ��ȡ�û�
 */
public final class PBUsrGetReq extends Message<PBUsrGetReq, PBUsrGetReq.Builder> {
  public static final ProtoAdapter<PBUsrGetReq> ADAPTER = new ProtoAdapter_PBUsrGetReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_UID = 0L;

  @WireField(
      tag = 1,
      adapter = "org.yeewoe.mopanet.protos.PBUserFilter#ADAPTER"
  )
  public final PBUserFilter filter;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long uid;

  public PBUsrGetReq(PBUserFilter filter, Long uid) {
    this(filter, uid, ByteString.EMPTY);
  }

  public PBUsrGetReq(PBUserFilter filter, Long uid, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.filter = filter;
    this.uid = uid;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.filter = filter;
    builder.uid = uid;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrGetReq)) return false;
    PBUsrGetReq o = (PBUsrGetReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(filter, o.filter)
        && Internal.equals(uid, o.uid);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (filter != null ? filter.hashCode() : 0);
      result = result * 37 + (uid != null ? uid.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (filter != null) builder.append(", filter=").append(filter);
    if (uid != null) builder.append(", uid=").append(uid);
    return builder.replace(0, 2, "PBUsrGetReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrGetReq, Builder> {
    public PBUserFilter filter;

    public Long uid;

    public Builder() {
    }

    public Builder filter(PBUserFilter filter) {
      this.filter = filter;
      return this;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    @Override
    public PBUsrGetReq build() {
      if (uid == null) {
        throw Internal.missingRequiredFields(uid, "uid");
      }
      return new PBUsrGetReq(filter, uid, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrGetReq extends ProtoAdapter<PBUsrGetReq> {
    ProtoAdapter_PBUsrGetReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrGetReq.class);
    }

    @Override
    public int encodedSize(PBUsrGetReq value) {
      return (value.filter != null ? PBUserFilter.ADAPTER.encodedSizeWithTag(1, value.filter) : 0)
          + ProtoAdapter.UINT64.encodedSizeWithTag(2, value.uid)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrGetReq value) throws IOException {
      if (value.filter != null) PBUserFilter.ADAPTER.encodeWithTag(writer, 1, value.filter);
      ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.uid);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrGetReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.filter(PBUserFilter.ADAPTER.decode(reader)); break;
          case 2: builder.uid(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrGetReq redact(PBUsrGetReq value) {
      Builder builder = value.newBuilder();
      if (builder.filter != null) builder.filter = PBUserFilter.ADAPTER.redact(builder.filter);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
