// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 567:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ��¼��֤��Ϊ���֣� 1.�����¼��2.ticket��¼
 * �����¼��ʹ���ֻ��ź������¼����¼���̷�Ϊ�������裺login��auth
 * ticket��¼: ���ٵ�¼���̣��������ӶϿ�����
 * �����¼֮login
 */
public final class PBUsrLoginReq extends Message<PBUsrLoginReq, PBUsrLoginReq.Builder> {
  public static final ProtoAdapter<PBUsrLoginReq> ADAPTER = new ProtoAdapter_PBUsrLoginReq();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_ACCOUNT = "";

  public static final String DEFAULT_VERSION = "";

  /**
   * 	�ֻ��ʺ�
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String account;

  /**
   * 	�ͻ���app�汾��
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String version;

  public PBUsrLoginReq(String account, String version) {
    this(account, version, ByteString.EMPTY);
  }

  public PBUsrLoginReq(String account, String version, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.account = account;
    this.version = version;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.account = account;
    builder.version = version;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrLoginReq)) return false;
    PBUsrLoginReq o = (PBUsrLoginReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(account, o.account)
        && Internal.equals(version, o.version);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (account != null ? account.hashCode() : 0);
      result = result * 37 + (version != null ? version.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (account != null) builder.append(", account=").append(account);
    if (version != null) builder.append(", version=").append(version);
    return builder.replace(0, 2, "PBUsrLoginReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrLoginReq, Builder> {
    public String account;

    public String version;

    public Builder() {
    }

    /**
     * 	�ֻ��ʺ�
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * 	�ͻ���app�汾��
     */
    public Builder version(String version) {
      this.version = version;
      return this;
    }

    @Override
    public PBUsrLoginReq build() {
      if (account == null) {
        throw Internal.missingRequiredFields(account, "account");
      }
      return new PBUsrLoginReq(account, version, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrLoginReq extends ProtoAdapter<PBUsrLoginReq> {
    ProtoAdapter_PBUsrLoginReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrLoginReq.class);
    }

    @Override
    public int encodedSize(PBUsrLoginReq value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.account)
          + (value.version != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.version) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrLoginReq value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.account);
      if (value.version != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.version);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrLoginReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.account(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.version(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrLoginReq redact(PBUsrLoginReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
