// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 591:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBUsrAuthRsp extends Message<PBUsrAuthRsp, PBUsrAuthRsp.Builder> {
  public static final ProtoAdapter<PBUsrAuthRsp> ADAPTER = new ProtoAdapter_PBUsrAuthRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  public static final Long DEFAULT_UID = 0L;

  public static final ByteString DEFAULT_TICKET = ByteString.EMPTY;

  /**
   * 	��֤�������Ϊ0��ʾʧ��
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  /**
   * 	��֤�ɹ��󣬷��ض�Ӧ���û�uid
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long uid;

  /**
   * 	���ص�ticketƱ��
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString ticket;

  public PBUsrAuthRsp(Integer result, Long uid, ByteString ticket) {
    this(result, uid, ticket, ByteString.EMPTY);
  }

  public PBUsrAuthRsp(Integer result, Long uid, ByteString ticket, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.uid = uid;
    this.ticket = ticket;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.uid = uid;
    builder.ticket = ticket;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrAuthRsp)) return false;
    PBUsrAuthRsp o = (PBUsrAuthRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(uid, o.uid)
        && Internal.equals(ticket, o.ticket);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (uid != null ? uid.hashCode() : 0);
      result_ = result_ * 37 + (ticket != null ? ticket.hashCode() : 0);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (uid != null) builder.append(", uid=").append(uid);
    if (ticket != null) builder.append(", ticket=").append(ticket);
    return builder.replace(0, 2, "PBUsrAuthRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrAuthRsp, Builder> {
    public Integer result;

    public Long uid;

    public ByteString ticket;

    public Builder() {
    }

    /**
     * 	��֤�������Ϊ0��ʾʧ��
     */
    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 	��֤�ɹ��󣬷��ض�Ӧ���û�uid
     */
    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    /**
     * 	���ص�ticketƱ��
     */
    public Builder ticket(ByteString ticket) {
      this.ticket = ticket;
      return this;
    }

    @Override
    public PBUsrAuthRsp build() {
      return new PBUsrAuthRsp(result, uid, ticket, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrAuthRsp extends ProtoAdapter<PBUsrAuthRsp> {
    ProtoAdapter_PBUsrAuthRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrAuthRsp.class);
    }

    @Override
    public int encodedSize(PBUsrAuthRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + (value.uid != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.uid) : 0)
          + (value.ticket != null ? ProtoAdapter.BYTES.encodedSizeWithTag(3, value.ticket) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrAuthRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.uid != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.uid);
      if (value.ticket != null) ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.ticket);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrAuthRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.uid(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.ticket(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrAuthRsp redact(PBUsrAuthRsp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
