// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 587:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * �����¼֮auth
 */
public final class PBUsrAuthReq extends Message<PBUsrAuthReq, PBUsrAuthReq.Builder> {
  public static final ProtoAdapter<PBUsrAuthReq> ADAPTER = new ProtoAdapter_PBUsrAuthReq();

  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_CHALLENGE_RESPONSE = ByteString.EMPTY;

  /**
   * 	����ս�Ļ�Ӧ
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES",
      label = WireField.Label.REQUIRED
  )
  public final ByteString challenge_response;

  public PBUsrAuthReq(ByteString challenge_response) {
    this(challenge_response, ByteString.EMPTY);
  }

  public PBUsrAuthReq(ByteString challenge_response, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.challenge_response = challenge_response;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.challenge_response = challenge_response;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrAuthReq)) return false;
    PBUsrAuthReq o = (PBUsrAuthReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(challenge_response, o.challenge_response);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (challenge_response != null ? challenge_response.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (challenge_response != null) builder.append(", challenge_response=").append(challenge_response);
    return builder.replace(0, 2, "PBUsrAuthReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrAuthReq, Builder> {
    public ByteString challenge_response;

    public Builder() {
    }

    /**
     * 	����ս�Ļ�Ӧ
     */
    public Builder challenge_response(ByteString challenge_response) {
      this.challenge_response = challenge_response;
      return this;
    }

    @Override
    public PBUsrAuthReq build() {
      if (challenge_response == null) {
        throw Internal.missingRequiredFields(challenge_response, "challenge_response");
      }
      return new PBUsrAuthReq(challenge_response, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrAuthReq extends ProtoAdapter<PBUsrAuthReq> {
    ProtoAdapter_PBUsrAuthReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrAuthReq.class);
    }

    @Override
    public int encodedSize(PBUsrAuthReq value) {
      return ProtoAdapter.BYTES.encodedSizeWithTag(1, value.challenge_response)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrAuthReq value) throws IOException {
      ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.challenge_response);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrAuthReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.challenge_response(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrAuthReq redact(PBUsrAuthReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
