// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 579:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBUsrLoginRsp extends Message<PBUsrLoginRsp, PBUsrLoginRsp.Builder> {
  public static final ProtoAdapter<PBUsrLoginRsp> ADAPTER = new ProtoAdapter_PBUsrLoginRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  public static final ByteString DEFAULT_CHALLENGE_SEED = ByteString.EMPTY;

  public static final Integer DEFAULT_CHALLENGE_ALGO = 0;

  /**
   * 	��¼�������Ϊ0��ʾʧ��
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  /**
   * 	��ս���ӡ�app��Ҫʹ��ָ�����㷨����ս���Ӽ��ܷ���
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString challenge_seed;

  /**
   * 	���õ���ս�㷨
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer challenge_algo;

  public PBUsrLoginRsp(Integer result, ByteString challenge_seed, Integer challenge_algo) {
    this(result, challenge_seed, challenge_algo, ByteString.EMPTY);
  }

  public PBUsrLoginRsp(Integer result, ByteString challenge_seed, Integer challenge_algo, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.challenge_seed = challenge_seed;
    this.challenge_algo = challenge_algo;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.challenge_seed = challenge_seed;
    builder.challenge_algo = challenge_algo;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrLoginRsp)) return false;
    PBUsrLoginRsp o = (PBUsrLoginRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(challenge_seed, o.challenge_seed)
        && Internal.equals(challenge_algo, o.challenge_algo);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (challenge_seed != null ? challenge_seed.hashCode() : 0);
      result_ = result_ * 37 + (challenge_algo != null ? challenge_algo.hashCode() : 0);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (challenge_seed != null) builder.append(", challenge_seed=").append(challenge_seed);
    if (challenge_algo != null) builder.append(", challenge_algo=").append(challenge_algo);
    return builder.replace(0, 2, "PBUsrLoginRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrLoginRsp, Builder> {
    public Integer result;

    public ByteString challenge_seed;

    public Integer challenge_algo;

    public Builder() {
    }

    /**
     * 	��¼�������Ϊ0��ʾʧ��
     */
    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 	��ս���ӡ�app��Ҫʹ��ָ�����㷨����ս���Ӽ��ܷ���
     */
    public Builder challenge_seed(ByteString challenge_seed) {
      this.challenge_seed = challenge_seed;
      return this;
    }

    /**
     * 	���õ���ս�㷨
     */
    public Builder challenge_algo(Integer challenge_algo) {
      this.challenge_algo = challenge_algo;
      return this;
    }

    @Override
    public PBUsrLoginRsp build() {
      return new PBUsrLoginRsp(result, challenge_seed, challenge_algo, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrLoginRsp extends ProtoAdapter<PBUsrLoginRsp> {
    ProtoAdapter_PBUsrLoginRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrLoginRsp.class);
    }

    @Override
    public int encodedSize(PBUsrLoginRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + (value.challenge_seed != null ? ProtoAdapter.BYTES.encodedSizeWithTag(2, value.challenge_seed) : 0)
          + (value.challenge_algo != null ? ProtoAdapter.INT32.encodedSizeWithTag(3, value.challenge_algo) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrLoginRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.challenge_seed != null) ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.challenge_seed);
      if (value.challenge_algo != null) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.challenge_algo);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrLoginRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.challenge_seed(ProtoAdapter.BYTES.decode(reader)); break;
          case 3: builder.challenge_algo(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrLoginRsp redact(PBUsrLoginRsp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
