// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 542:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBUsrGetRsp extends Message<PBUsrGetRsp, PBUsrGetRsp.Builder> {
  public static final ProtoAdapter<PBUsrGetRsp> ADAPTER = new ProtoAdapter_PBUsrGetRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  @WireField(
      tag = 2,
      adapter = "org.yeewoe.mopanet.protos.PBUser#ADAPTER"
  )
  public final PBUser user;

  public PBUsrGetRsp(Integer result, PBUser user) {
    this(result, user, ByteString.EMPTY);
  }

  public PBUsrGetRsp(Integer result, PBUser user, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.user = user;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.user = user;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrGetRsp)) return false;
    PBUsrGetRsp o = (PBUsrGetRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(user, o.user);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (user != null ? user.hashCode() : 0);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (user != null) builder.append(", user=").append(user);
    return builder.replace(0, 2, "PBUsrGetRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrGetRsp, Builder> {
    public Integer result;

    public PBUser user;

    public Builder() {
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    public Builder user(PBUser user) {
      this.user = user;
      return this;
    }

    @Override
    public PBUsrGetRsp build() {
      return new PBUsrGetRsp(result, user, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrGetRsp extends ProtoAdapter<PBUsrGetRsp> {
    ProtoAdapter_PBUsrGetRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrGetRsp.class);
    }

    @Override
    public int encodedSize(PBUsrGetRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + (value.user != null ? PBUser.ADAPTER.encodedSizeWithTag(2, value.user) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrGetRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.user != null) PBUser.ADAPTER.encodeWithTag(writer, 2, value.user);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrGetRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.user(PBUser.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrGetRsp redact(PBUsrGetRsp value) {
      Builder builder = value.newBuilder();
      if (builder.user != null) builder.user = PBUser.ADAPTER.redact(builder.user);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
