// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 466:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PBUser extends Message<PBUser, PBUser.Builder> {
  public static final ProtoAdapter<PBUser> ADAPTER = new ProtoAdapter_PBUser();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_UID = 0L;

  public static final String DEFAULT_ACCOUNT = "";

  public static final String DEFAULT_NAME = "";

  public static final Integer DEFAULT_STAR = 0;

  public static final Integer DEFAULT_SEX = 0;

  public static final Integer DEFAULT_AGE = 0;

  public static final ByteString DEFAULT_PHOTO = ByteString.EMPTY;

  public static final ByteString DEFAULT_THUMB = ByteString.EMPTY;

  public static final String DEFAULT_SIGNATURE = "";

  public static final Integer DEFAULT_EMOTION = 0;

  public static final String DEFAULT_JOB = "";

  public static final Integer DEFAULT_COLLEGE = 0;

  public static final String DEFAULT_HOMELAND = "";

  public static final String DEFAULT_SPORT = "";

  public static final String DEFAULT_MUSIC = "";

  public static final String DEFAULT_MOVIE = "";

  public static final String DEFAULT_FOOD = "";

  public static final String DEFAULT_BOOK = "";

  public static final String DEFAULT_TRAVAL = "";

  public static final String DEFAULT_WORKPLACE = "";

  public static final String DEFAULT_HAUNTPLACE = "";

  public static final String DEFAULT_DESC = "";

  public static final Long DEFAULT_REGTIME = 0L;

  /**
   * 	�û�ID���ɷ���˷��䣩
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long uid;

  /**
   * 	�û��˺ţ��ֻ����룩
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String account;

  /**
   * 	�û�����
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String name;

  /**
   * 	�Ǽ�
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer star;

  /**
   * 	�Ա�
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer sex;

  /**
   * 	�������������ֶ�,������һ���ֽ�Ϊ���䣬�����ڶ���Ϊ����
   */
  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer age;

  /**
   * 	ͷ��
   */
  @WireField(
      tag = 10,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString photo;

  /**
   * 	ͷ�������ͼ
   */
  @WireField(
      tag = 11,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString thumb;

  /**
   * 	�û�����ǩ��
   */
  @WireField(
      tag = 13,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String signature;

  /**
   * 	���״̬
   */
  @WireField(
      tag = 14,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer emotion;

  /**
   * 	ְҵ,��ʽ"�����|С����"
   */
  @WireField(
      tag = 15,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String job;

  /**
   * 	ԺУ
   */
  @WireField(
      tag = 16,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer college;

  /**
   * 	����
   */
  @WireField(
      tag = 17,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String homeland;

  /**
   * 	ϲ�����˶�
   */
  @WireField(
      tag = 18,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String sport;

  /**
   * 	ϲ��������
   */
  @WireField(
      tag = 19,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String music;

  /**
   * 	ϲ���ĵ�Ӱ
   */
  @WireField(
      tag = 20,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String movie;

  /**
   * 	ϲ����ʳ��
   */
  @WireField(
      tag = 21,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String food;

  /**
   * 	ϲ�����鼮
   */
  @WireField(
      tag = 22,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String book;

  /**
   * 	�����㼣
   */
  @WireField(
      tag = 23,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String traval;

  /**
   * 	�����ص�
   */
  @WireField(
      tag = 24,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String workplace;

  /**
   * 	����û��
   */
  @WireField(
      tag = 25,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String hauntplace;

  /**
   * 	��������
   */
  @WireField(
      tag = 26,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String desc;

  /**
   * 	ע��ʱ��
   */
  @WireField(
      tag = 27,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long regtime;

  public PBUser(Long uid, String account, String name, Integer star, Integer sex, Integer age, ByteString photo, ByteString thumb, String signature, Integer emotion, String job, Integer college, String homeland, String sport, String music, String movie, String food, String book, String traval, String workplace, String hauntplace, String desc, Long regtime) {
    this(uid, account, name, star, sex, age, photo, thumb, signature, emotion, job, college, homeland, sport, music, movie, food, book, traval, workplace, hauntplace, desc, regtime, ByteString.EMPTY);
  }

  public PBUser(Long uid, String account, String name, Integer star, Integer sex, Integer age, ByteString photo, ByteString thumb, String signature, Integer emotion, String job, Integer college, String homeland, String sport, String music, String movie, String food, String book, String traval, String workplace, String hauntplace, String desc, Long regtime, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.uid = uid;
    this.account = account;
    this.name = name;
    this.star = star;
    this.sex = sex;
    this.age = age;
    this.photo = photo;
    this.thumb = thumb;
    this.signature = signature;
    this.emotion = emotion;
    this.job = job;
    this.college = college;
    this.homeland = homeland;
    this.sport = sport;
    this.music = music;
    this.movie = movie;
    this.food = food;
    this.book = book;
    this.traval = traval;
    this.workplace = workplace;
    this.hauntplace = hauntplace;
    this.desc = desc;
    this.regtime = regtime;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.uid = uid;
    builder.account = account;
    builder.name = name;
    builder.star = star;
    builder.sex = sex;
    builder.age = age;
    builder.photo = photo;
    builder.thumb = thumb;
    builder.signature = signature;
    builder.emotion = emotion;
    builder.job = job;
    builder.college = college;
    builder.homeland = homeland;
    builder.sport = sport;
    builder.music = music;
    builder.movie = movie;
    builder.food = food;
    builder.book = book;
    builder.traval = traval;
    builder.workplace = workplace;
    builder.hauntplace = hauntplace;
    builder.desc = desc;
    builder.regtime = regtime;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUser)) return false;
    PBUser o = (PBUser) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(uid, o.uid)
        && Internal.equals(account, o.account)
        && Internal.equals(name, o.name)
        && Internal.equals(star, o.star)
        && Internal.equals(sex, o.sex)
        && Internal.equals(age, o.age)
        && Internal.equals(photo, o.photo)
        && Internal.equals(thumb, o.thumb)
        && Internal.equals(signature, o.signature)
        && Internal.equals(emotion, o.emotion)
        && Internal.equals(job, o.job)
        && Internal.equals(college, o.college)
        && Internal.equals(homeland, o.homeland)
        && Internal.equals(sport, o.sport)
        && Internal.equals(music, o.music)
        && Internal.equals(movie, o.movie)
        && Internal.equals(food, o.food)
        && Internal.equals(book, o.book)
        && Internal.equals(traval, o.traval)
        && Internal.equals(workplace, o.workplace)
        && Internal.equals(hauntplace, o.hauntplace)
        && Internal.equals(desc, o.desc)
        && Internal.equals(regtime, o.regtime);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (uid != null ? uid.hashCode() : 0);
      result = result * 37 + (account != null ? account.hashCode() : 0);
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (star != null ? star.hashCode() : 0);
      result = result * 37 + (sex != null ? sex.hashCode() : 0);
      result = result * 37 + (age != null ? age.hashCode() : 0);
      result = result * 37 + (photo != null ? photo.hashCode() : 0);
      result = result * 37 + (thumb != null ? thumb.hashCode() : 0);
      result = result * 37 + (signature != null ? signature.hashCode() : 0);
      result = result * 37 + (emotion != null ? emotion.hashCode() : 0);
      result = result * 37 + (job != null ? job.hashCode() : 0);
      result = result * 37 + (college != null ? college.hashCode() : 0);
      result = result * 37 + (homeland != null ? homeland.hashCode() : 0);
      result = result * 37 + (sport != null ? sport.hashCode() : 0);
      result = result * 37 + (music != null ? music.hashCode() : 0);
      result = result * 37 + (movie != null ? movie.hashCode() : 0);
      result = result * 37 + (food != null ? food.hashCode() : 0);
      result = result * 37 + (book != null ? book.hashCode() : 0);
      result = result * 37 + (traval != null ? traval.hashCode() : 0);
      result = result * 37 + (workplace != null ? workplace.hashCode() : 0);
      result = result * 37 + (hauntplace != null ? hauntplace.hashCode() : 0);
      result = result * 37 + (desc != null ? desc.hashCode() : 0);
      result = result * 37 + (regtime != null ? regtime.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (uid != null) builder.append(", uid=").append(uid);
    if (account != null) builder.append(", account=").append(account);
    if (name != null) builder.append(", name=").append(name);
    if (star != null) builder.append(", star=").append(star);
    if (sex != null) builder.append(", sex=").append(sex);
    if (age != null) builder.append(", age=").append(age);
    if (photo != null) builder.append(", photo=").append(photo);
    if (thumb != null) builder.append(", thumb=").append(thumb);
    if (signature != null) builder.append(", signature=").append(signature);
    if (emotion != null) builder.append(", emotion=").append(emotion);
    if (job != null) builder.append(", job=").append(job);
    if (college != null) builder.append(", college=").append(college);
    if (homeland != null) builder.append(", homeland=").append(homeland);
    if (sport != null) builder.append(", sport=").append(sport);
    if (music != null) builder.append(", music=").append(music);
    if (movie != null) builder.append(", movie=").append(movie);
    if (food != null) builder.append(", food=").append(food);
    if (book != null) builder.append(", book=").append(book);
    if (traval != null) builder.append(", traval=").append(traval);
    if (workplace != null) builder.append(", workplace=").append(workplace);
    if (hauntplace != null) builder.append(", hauntplace=").append(hauntplace);
    if (desc != null) builder.append(", desc=").append(desc);
    if (regtime != null) builder.append(", regtime=").append(regtime);
    return builder.replace(0, 2, "PBUser{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUser, Builder> {
    public Long uid;

    public String account;

    public String name;

    public Integer star;

    public Integer sex;

    public Integer age;

    public ByteString photo;

    public ByteString thumb;

    public String signature;

    public Integer emotion;

    public String job;

    public Integer college;

    public String homeland;

    public String sport;

    public String music;

    public String movie;

    public String food;

    public String book;

    public String traval;

    public String workplace;

    public String hauntplace;

    public String desc;

    public Long regtime;

    public Builder() {
    }

    /**
     * 	�û�ID���ɷ���˷��䣩
     */
    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    /**
     * 	�û��˺ţ��ֻ����룩
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * 	�û�����
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * 	�Ǽ�
     */
    public Builder star(Integer star) {
      this.star = star;
      return this;
    }

    /**
     * 	�Ա�
     */
    public Builder sex(Integer sex) {
      this.sex = sex;
      return this;
    }

    /**
     * 	�������������ֶ�,������һ���ֽ�Ϊ���䣬�����ڶ���Ϊ����
     */
    public Builder age(Integer age) {
      this.age = age;
      return this;
    }

    /**
     * 	ͷ��
     */
    public Builder photo(ByteString photo) {
      this.photo = photo;
      return this;
    }

    /**
     * 	ͷ�������ͼ
     */
    public Builder thumb(ByteString thumb) {
      this.thumb = thumb;
      return this;
    }

    /**
     * 	�û�����ǩ��
     */
    public Builder signature(String signature) {
      this.signature = signature;
      return this;
    }

    /**
     * 	���״̬
     */
    public Builder emotion(Integer emotion) {
      this.emotion = emotion;
      return this;
    }

    /**
     * 	ְҵ,��ʽ"�����|С����"
     */
    public Builder job(String job) {
      this.job = job;
      return this;
    }

    /**
     * 	ԺУ
     */
    public Builder college(Integer college) {
      this.college = college;
      return this;
    }

    /**
     * 	����
     */
    public Builder homeland(String homeland) {
      this.homeland = homeland;
      return this;
    }

    /**
     * 	ϲ�����˶�
     */
    public Builder sport(String sport) {
      this.sport = sport;
      return this;
    }

    /**
     * 	ϲ��������
     */
    public Builder music(String music) {
      this.music = music;
      return this;
    }

    /**
     * 	ϲ���ĵ�Ӱ
     */
    public Builder movie(String movie) {
      this.movie = movie;
      return this;
    }

    /**
     * 	ϲ����ʳ��
     */
    public Builder food(String food) {
      this.food = food;
      return this;
    }

    /**
     * 	ϲ�����鼮
     */
    public Builder book(String book) {
      this.book = book;
      return this;
    }

    /**
     * 	�����㼣
     */
    public Builder traval(String traval) {
      this.traval = traval;
      return this;
    }

    /**
     * 	�����ص�
     */
    public Builder workplace(String workplace) {
      this.workplace = workplace;
      return this;
    }

    /**
     * 	����û��
     */
    public Builder hauntplace(String hauntplace) {
      this.hauntplace = hauntplace;
      return this;
    }

    /**
     * 	��������
     */
    public Builder desc(String desc) {
      this.desc = desc;
      return this;
    }

    /**
     * 	ע��ʱ��
     */
    public Builder regtime(Long regtime) {
      this.regtime = regtime;
      return this;
    }

    @Override
    public PBUser build() {
      if (uid == null
          || account == null) {
        throw Internal.missingRequiredFields(uid, "uid",
            account, "account");
      }
      return new PBUser(uid, account, name, star, sex, age, photo, thumb, signature, emotion, job, college, homeland, sport, music, movie, food, book, traval, workplace, hauntplace, desc, regtime, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUser extends ProtoAdapter<PBUser> {
    ProtoAdapter_PBUser() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUser.class);
    }

    @Override
    public int encodedSize(PBUser value) {
      return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.uid)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.account)
          + (value.name != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.name) : 0)
          + (value.star != null ? ProtoAdapter.INT32.encodedSizeWithTag(4, value.star) : 0)
          + (value.sex != null ? ProtoAdapter.INT32.encodedSizeWithTag(5, value.sex) : 0)
          + (value.age != null ? ProtoAdapter.INT32.encodedSizeWithTag(6, value.age) : 0)
          + (value.photo != null ? ProtoAdapter.BYTES.encodedSizeWithTag(10, value.photo) : 0)
          + (value.thumb != null ? ProtoAdapter.BYTES.encodedSizeWithTag(11, value.thumb) : 0)
          + (value.signature != null ? ProtoAdapter.STRING.encodedSizeWithTag(13, value.signature) : 0)
          + (value.emotion != null ? ProtoAdapter.INT32.encodedSizeWithTag(14, value.emotion) : 0)
          + (value.job != null ? ProtoAdapter.STRING.encodedSizeWithTag(15, value.job) : 0)
          + (value.college != null ? ProtoAdapter.INT32.encodedSizeWithTag(16, value.college) : 0)
          + (value.homeland != null ? ProtoAdapter.STRING.encodedSizeWithTag(17, value.homeland) : 0)
          + (value.sport != null ? ProtoAdapter.STRING.encodedSizeWithTag(18, value.sport) : 0)
          + (value.music != null ? ProtoAdapter.STRING.encodedSizeWithTag(19, value.music) : 0)
          + (value.movie != null ? ProtoAdapter.STRING.encodedSizeWithTag(20, value.movie) : 0)
          + (value.food != null ? ProtoAdapter.STRING.encodedSizeWithTag(21, value.food) : 0)
          + (value.book != null ? ProtoAdapter.STRING.encodedSizeWithTag(22, value.book) : 0)
          + (value.traval != null ? ProtoAdapter.STRING.encodedSizeWithTag(23, value.traval) : 0)
          + (value.workplace != null ? ProtoAdapter.STRING.encodedSizeWithTag(24, value.workplace) : 0)
          + (value.hauntplace != null ? ProtoAdapter.STRING.encodedSizeWithTag(25, value.hauntplace) : 0)
          + (value.desc != null ? ProtoAdapter.STRING.encodedSizeWithTag(26, value.desc) : 0)
          + (value.regtime != null ? ProtoAdapter.UINT64.encodedSizeWithTag(27, value.regtime) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUser value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.uid);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.account);
      if (value.name != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.name);
      if (value.star != null) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.star);
      if (value.sex != null) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.sex);
      if (value.age != null) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.age);
      if (value.photo != null) ProtoAdapter.BYTES.encodeWithTag(writer, 10, value.photo);
      if (value.thumb != null) ProtoAdapter.BYTES.encodeWithTag(writer, 11, value.thumb);
      if (value.signature != null) ProtoAdapter.STRING.encodeWithTag(writer, 13, value.signature);
      if (value.emotion != null) ProtoAdapter.INT32.encodeWithTag(writer, 14, value.emotion);
      if (value.job != null) ProtoAdapter.STRING.encodeWithTag(writer, 15, value.job);
      if (value.college != null) ProtoAdapter.INT32.encodeWithTag(writer, 16, value.college);
      if (value.homeland != null) ProtoAdapter.STRING.encodeWithTag(writer, 17, value.homeland);
      if (value.sport != null) ProtoAdapter.STRING.encodeWithTag(writer, 18, value.sport);
      if (value.music != null) ProtoAdapter.STRING.encodeWithTag(writer, 19, value.music);
      if (value.movie != null) ProtoAdapter.STRING.encodeWithTag(writer, 20, value.movie);
      if (value.food != null) ProtoAdapter.STRING.encodeWithTag(writer, 21, value.food);
      if (value.book != null) ProtoAdapter.STRING.encodeWithTag(writer, 22, value.book);
      if (value.traval != null) ProtoAdapter.STRING.encodeWithTag(writer, 23, value.traval);
      if (value.workplace != null) ProtoAdapter.STRING.encodeWithTag(writer, 24, value.workplace);
      if (value.hauntplace != null) ProtoAdapter.STRING.encodeWithTag(writer, 25, value.hauntplace);
      if (value.desc != null) ProtoAdapter.STRING.encodeWithTag(writer, 26, value.desc);
      if (value.regtime != null) ProtoAdapter.UINT64.encodeWithTag(writer, 27, value.regtime);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUser decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.uid(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.account(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.star(ProtoAdapter.INT32.decode(reader)); break;
          case 5: builder.sex(ProtoAdapter.INT32.decode(reader)); break;
          case 6: builder.age(ProtoAdapter.INT32.decode(reader)); break;
          case 10: builder.photo(ProtoAdapter.BYTES.decode(reader)); break;
          case 11: builder.thumb(ProtoAdapter.BYTES.decode(reader)); break;
          case 13: builder.signature(ProtoAdapter.STRING.decode(reader)); break;
          case 14: builder.emotion(ProtoAdapter.INT32.decode(reader)); break;
          case 15: builder.job(ProtoAdapter.STRING.decode(reader)); break;
          case 16: builder.college(ProtoAdapter.INT32.decode(reader)); break;
          case 17: builder.homeland(ProtoAdapter.STRING.decode(reader)); break;
          case 18: builder.sport(ProtoAdapter.STRING.decode(reader)); break;
          case 19: builder.music(ProtoAdapter.STRING.decode(reader)); break;
          case 20: builder.movie(ProtoAdapter.STRING.decode(reader)); break;
          case 21: builder.food(ProtoAdapter.STRING.decode(reader)); break;
          case 22: builder.book(ProtoAdapter.STRING.decode(reader)); break;
          case 23: builder.traval(ProtoAdapter.STRING.decode(reader)); break;
          case 24: builder.workplace(ProtoAdapter.STRING.decode(reader)); break;
          case 25: builder.hauntplace(ProtoAdapter.STRING.decode(reader)); break;
          case 26: builder.desc(ProtoAdapter.STRING.decode(reader)); break;
          case 27: builder.regtime(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUser redact(PBUser value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
