// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 645:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * ��ע/ȡ����ע
 */
public enum PBUsrFollowOp implements WireEnum {
  UFOP_ADD(1),

  UFOP_DEL(2);

  public static final ProtoAdapter<PBUsrFollowOp> ADAPTER = ProtoAdapter.newEnumAdapter(PBUsrFollowOp.class);

  private final int value;

  PBUsrFollowOp(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static PBUsrFollowOp fromValue(int value) {
    switch (value) {
      case 1: return UFOP_ADD;
      case 2: return UFOP_DEL;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
