// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 516:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * ɾ���û�
 */
public final class PBUsrRemoveReq extends Message<PBUsrRemoveReq, PBUsrRemoveReq.Builder> {
  public static final ProtoAdapter<PBUsrRemoveReq> ADAPTER = new ProtoAdapter_PBUsrRemoveReq();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REPEATED
  )
  public final List<Long> uids;

  public PBUsrRemoveReq(List<Long> uids) {
    this(uids, ByteString.EMPTY);
  }

  public PBUsrRemoveReq(List<Long> uids, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.uids = Internal.immutableCopyOf("uids", uids);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.uids = Internal.copyOf("uids", uids);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrRemoveReq)) return false;
    PBUsrRemoveReq o = (PBUsrRemoveReq) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(uids, o.uids);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (uids != null ? uids.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (uids != null) builder.append(", uids=").append(uids);
    return builder.replace(0, 2, "PBUsrRemoveReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrRemoveReq, Builder> {
    public List<Long> uids;

    public Builder() {
      uids = Internal.newMutableList();
    }

    public Builder uids(List<Long> uids) {
      Internal.checkElementsNotNull(uids);
      this.uids = uids;
      return this;
    }

    @Override
    public PBUsrRemoveReq build() {
      return new PBUsrRemoveReq(uids, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrRemoveReq extends ProtoAdapter<PBUsrRemoveReq> {
    ProtoAdapter_PBUsrRemoveReq() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrRemoveReq.class);
    }

    @Override
    public int encodedSize(PBUsrRemoveReq value) {
      return ProtoAdapter.UINT64.asRepeated().encodedSizeWithTag(1, value.uids)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrRemoveReq value) throws IOException {
      if (value.uids != null) ProtoAdapter.UINT64.asRepeated().encodeWithTag(writer, 1, value.uids);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrRemoveReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.uids.add(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrRemoveReq redact(PBUsrRemoveReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
