// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: merge.proto at 665:1
package org.yeewoe.mopanet.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class PBUsrFollowListRsp extends Message<PBUsrFollowListRsp, PBUsrFollowListRsp.Builder> {
  public static final ProtoAdapter<PBUsrFollowListRsp> ADAPTER = new ProtoAdapter_PBUsrFollowListRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RESULT = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer result;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REPEATED
  )
  public final List<Long> uids;

  public PBUsrFollowListRsp(Integer result, List<Long> uids) {
    this(result, uids, ByteString.EMPTY);
  }

  public PBUsrFollowListRsp(Integer result, List<Long> uids, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.result = result;
    this.uids = Internal.immutableCopyOf("uids", uids);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.result = result;
    builder.uids = Internal.copyOf("uids", uids);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PBUsrFollowListRsp)) return false;
    PBUsrFollowListRsp o = (PBUsrFollowListRsp) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(result, o.result)
        && Internal.equals(uids, o.uids);
  }

  @Override
  public int hashCode() {
    int result_ = super.hashCode;
    if (result_ == 0) {
      result_ = unknownFields().hashCode();
      result_ = result_ * 37 + (result != null ? result.hashCode() : 0);
      result_ = result_ * 37 + (uids != null ? uids.hashCode() : 1);
      super.hashCode = result_;
    }
    return result_;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (result != null) builder.append(", result=").append(result);
    if (uids != null) builder.append(", uids=").append(uids);
    return builder.replace(0, 2, "PBUsrFollowListRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PBUsrFollowListRsp, Builder> {
    public Integer result;

    public List<Long> uids;

    public Builder() {
      uids = Internal.newMutableList();
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    public Builder uids(List<Long> uids) {
      Internal.checkElementsNotNull(uids);
      this.uids = uids;
      return this;
    }

    @Override
    public PBUsrFollowListRsp build() {
      return new PBUsrFollowListRsp(result, uids, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PBUsrFollowListRsp extends ProtoAdapter<PBUsrFollowListRsp> {
    ProtoAdapter_PBUsrFollowListRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, PBUsrFollowListRsp.class);
    }

    @Override
    public int encodedSize(PBUsrFollowListRsp value) {
      return (value.result != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.result) : 0)
          + ProtoAdapter.UINT64.asRepeated().encodedSizeWithTag(2, value.uids)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PBUsrFollowListRsp value) throws IOException {
      if (value.result != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.result);
      if (value.uids != null) ProtoAdapter.UINT64.asRepeated().encodeWithTag(writer, 2, value.uids);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PBUsrFollowListRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.result(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.uids.add(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PBUsrFollowListRsp redact(PBUsrFollowListRsp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
